//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.11 at 03:35:05 PM BRST 
//


package com.dieboldnixdorf.frentecaixa.domain;

import java.io.Serializable;
import java.math.BigDecimal;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;


/**
 * <p>Java class for DiariasConsolidadasPayloadType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DiariasConsolidadasPayloadType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="statusOperacao"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
 *               &lt;enumeration value="0"/&gt;
 *               &lt;enumeration value="1"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="codigoCarrefourProduto"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
 *               &lt;maxExclusive value="9999999999999"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="numeroPDV" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="quantidadeTotalVendida" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="valorTotalVendido" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="quantidadeTotalVendidaDesconto" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="valorTotalVendidoDesconto" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DiariasConsolidadasPayloadType", propOrder = {
	"siglaLoja",
    "statusOperacao",
    "codigoCarrefourProduto",
    "numeroPDV",
    "quantidadeTotalVendida",
    "valorTotalVendido",
    "quantidadeTotalVendidaDesconto",
    "valorTotalVendidoDesconto"
})
@JsonPropertyOrder({ 
	"siglaLoja",
    "statusOperacao",
    "codigoCarrefourProduto",
    "numeroPDV",
    "quantidadeTotalVendida",
    "valorTotalVendido",
    "quantidadeTotalVendidaDesconto",
    "valorTotalVendidoDesconto"
})
public class DiariasConsolidadasPayloadType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    protected String siglaLoja;
    protected int statusOperacao;
    @XmlElement(required = true)
    protected Long codigoCarrefourProduto;
    protected Long numeroPDV;
    @JsonProperty("quantidadeTotalVendida")
    @JsonSerialize(using = BigDecimal7Serializer.class)
    protected BigDecimal quantidadeTotalVendida;
    @JsonProperty("valorTotalVendido")
    @JsonSerialize(using = BigDecimalSerializer.class)
    protected BigDecimal valorTotalVendido;
    @JsonProperty("quantidadeTotalVendidaDesconto")
    @JsonSerialize(using = BigDecimal7Serializer.class)
    protected BigDecimal quantidadeTotalVendidaDesconto;
    @JsonProperty("valorTotalVendidoDesconto")
    @JsonSerialize(using = BigDecimalSerializer.class)
    protected BigDecimal valorTotalVendidoDesconto;

    /**
     * Gets the value of the siglaLoja property.
     *
     * @return the sigla loja
     */
    public String getSiglaLoja() {
		return siglaLoja;
	}

    /**
     * Sets the value of the siglaLoja property.
     * 
     */
	public void setSiglaLoja(String siglaLoja) {
		this.siglaLoja = siglaLoja;
	}

    /**
     * Gets the value of the statusOperacao property.
     * 
     */
    public int getStatusOperacao() {
        return statusOperacao;
    }

    /**
     * Sets the value of the statusOperacao property.
     * 
     */
    public void setStatusOperacao(int value) {
        this.statusOperacao = value;
    }

    /**
     * Gets the value of the codigoCarrefourProduto property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getCodigoCarrefourProduto() {
        return codigoCarrefourProduto;
    }

    /**
     * Sets the value of the codigoCarrefourProduto property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setCodigoCarrefourProduto(Long value) {
        this.codigoCarrefourProduto = value;
    }

    /**
     * Gets the value of the numeroPDV property.
     * 
     */
    public Long getNumeroPDV() {
        return numeroPDV;
    }

    /**
     * Sets the value of the numeroPDV property.
     * 
     */
    public void setNumeroPDV(Long value) {
        this.numeroPDV = value;
    }

    /**
     * Gets the value of the quantidadeTotalVendida property.
     * 
     */
    public BigDecimal getQuantidadeTotalVendida() {
        return quantidadeTotalVendida;
    }

    /**
     * Sets the value of the quantidadeTotalVendida property.
     * 
     */
    public void setQuantidadeTotalVendida(BigDecimal value) {
        this.quantidadeTotalVendida = value;
    }

    /**
     * Gets the value of the valorTotalVendido property.
     * 
     */
    public BigDecimal getValorTotalVendido() {
        return valorTotalVendido;
    }

    /**
     * Sets the value of the valorTotalVendido property.
     * 
     */
    public void setValorTotalVendido(BigDecimal value) {
        this.valorTotalVendido = value;
    }

    /**
     * Gets the value of the quantidadeTotalVendidaDesconto property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public BigDecimal getQuantidadeTotalVendidaDesconto() {
        return quantidadeTotalVendidaDesconto;
    }

    /**
     * Sets the value of the quantidadeTotalVendidaDesconto property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setQuantidadeTotalVendidaDesconto(BigDecimal value) {
        this.quantidadeTotalVendidaDesconto = value;
    }

    /**
     * Gets the value of the valorTotalVendidoDesconto property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValorTotalVendidoDesconto() {
        return valorTotalVendidoDesconto;
    }

    /**
     * Sets the value of the valorTotalVendidoDesconto property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValorTotalVendidoDesconto(BigDecimal value) {
        this.valorTotalVendidoDesconto = value;
    }

}
