//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.11 at 03:35:05 PM BRST 
//


package com.dieboldnixdorf.frentecaixa.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Calendar;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;


/**
 * <p>Java class for RebaixaPrecoPayloadType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RebaixaPrecoPayloadType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="numeroPDV"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
 *               &lt;maxExclusive value="999"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="numeroTransacao"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
 *               &lt;maxExclusive value="99999"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="recepcionistaDRT"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}long"&gt;
 *               &lt;maxExclusive value="999999999"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="codigoProduto"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}long"&gt;
 *               &lt;maxExclusive value="9999999999999"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="valorOriginal" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="valorFinal" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="quantidadeItens" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="status"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="R"/&gt;
 *               &lt;enumeration value="V"/&gt;
 *               &lt;enumeration value="B"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="dataValidade" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RebaixaPrecoPayloadType", propOrder = {
    "numeroPDV",
    "numeroTransacao",
    "recepcionistaDRT",
    "codigoProduto",
    "valorOriginal",
    "valorFinal",
    "quantidadeItens",
    "status",
    "dataValidade"
})
@JsonPropertyOrder({ 
    "numeroPDV",
    "numeroTransacao",
    "recepcionistaDRT",
    "codigoProduto",
    "valorOriginal",
    "valorFinal",
    "quantidadeItens",
    "status",
    "dataValidade"
})
public class RebaixaPrecoPayloadType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    protected int numeroPDV;
    protected Long numeroTransacao;
    protected Long recepcionistaDRT;
    protected Long codigoProduto;
    @XmlElement(required = true)
    @JsonProperty("valorOriginal")
    @JsonSerialize(using = BigDecimalSerializer.class)
    protected BigDecimal valorOriginal;
    @XmlElement(required = true)
    @JsonProperty("valorFinal")
    @JsonSerialize(using = BigDecimalSerializer.class)
    protected BigDecimal valorFinal;
    @XmlElement(required = true)
    @JsonProperty("quantidadeItens")
    @JsonSerialize(using = BigDecimal3Serializer.class)
    protected BigDecimal quantidadeItens;
    @XmlElement(required = true)
    protected String status;
    @XmlSchemaType(name = "date")
    @JsonProperty("dataValidade")
    @JsonSerialize(using = DataValidadeSerializer.class)
    @JsonInclude(Include.NON_NULL)
    protected Calendar dataValidade;

    /**
     * Gets the value of the numeroPDV property.
     * 
     */
    public int getNumeroPDV() {
        return numeroPDV;
    }

    /**
     * Sets the value of the numeroPDV property.
     * 
     */
    public void setNumeroPDV(int value) {
        this.numeroPDV = value;
    }

    /**
     * Gets the value of the numeroTransacao property.
     * 
     */
    public Long getNumeroTransacao() {
        return numeroTransacao;
    }

    /**
     * Sets the value of the numeroTransacao property.
     * 
     */
    public void setNumeroTransacao(Long value) {
        this.numeroTransacao = value;
    }

    /**
     * Gets the value of the recepcionistaDRT property.
     * 
     */
    public Long getRecepcionistaDRT() {
        return recepcionistaDRT;
    }

    /**
     * Sets the value of the recepcionistaDRT property.
     * 
     */
    public void setRecepcionistaDRT(Long value) {
        this.recepcionistaDRT = value;
    }

    /**
     * Gets the value of the codigoProduto property.
     * 
     */
    public Long getCodigoProduto() {
        return codigoProduto;
    }

    /**
     * Sets the value of the codigoProduto property.
     * 
     */
    public void setCodigoProduto(Long value) {
        this.codigoProduto = value;
    }

    /**
     * Gets the value of the valorOriginal property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValorOriginal() {
        return valorOriginal;
    }

    /**
     * Sets the value of the valorOriginal property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValorOriginal(BigDecimal value) {
        this.valorOriginal = value;
    }

    /**
     * Gets the value of the valorFinal property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValorFinal() {
        return valorFinal;
    }

    /**
     * Sets the value of the valorFinal property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValorFinal(BigDecimal value) {
        this.valorFinal = value;
    }

    /**
     * Gets the value of the quantidadeItens property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getQuantidadeItens() {
        return quantidadeItens;
    }

    /**
     * Sets the value of the quantidadeItens property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setQuantidadeItens(BigDecimal value) {
        this.quantidadeItens = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the dataValidade property.
     * 
     * @return
     *     possible object is
     *     {@link Calendar }
     *     
     */
    public Calendar getDataValidade() {
        return dataValidade;
    }

    /**
     * Sets the value of the dataValidade property.
     * 
     * @param value
     *     allowed object is
     *     {@link Calendar }
     *     
     */
    public void setDataValidade(Calendar value) {
        this.dataValidade = value;
    }

}
