//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.11 at 03:35:05 PM BRST 
//


package com.dieboldnixdorf.frentecaixa.domain;

import java.io.Serializable;
import java.math.BigDecimal;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TipoDrogariaTransacaoType", propOrder = {
    "codigoTransacaoInterno",
    "contadorRegistroInterno",
    "PK",
    "codigoPBM",
    "valorPBM",
    "numeroPreVendaPBM",
    "codigoAutorizacaoPBM",
    "numeroPedidoPBM",
    "codigoRMSProduto",
    "qtdeVendida",
    "horaMinutoEvento"
})
@JsonPropertyOrder({ 
    "codigoTransacaoInterno",
    "contadorRegistroInterno",
    "PK",
    "codigoPBM",
    "valorPBM",
    "numeroPreVendaPBM",
    "codigoAutorizacaoPBM",
    "numeroPedidoPBM",
    "codigoRMSProduto",
    "qtdeVendida",
    "horaMinutoEvento"
})
public class TipoDrogariaTransacaoType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    
    
    protected Long codigoPBM;
    
    @JsonProperty("valorPBM")
    @JsonSerialize(using = BigDecimal8Serializer.class)
    protected BigDecimal valorPBM;
    
    protected Long numeroPreVendaPBM;
    protected Long codigoAutorizacaoPBM;
    protected Long numeroPedidoPBM;
    
    @XmlElement(required = true)
    protected String horaMinutoEvento;
    protected Long pk;
    protected int codigoTransacaoInterno;
    
    protected Long codigoRMSProduto;
    
	@JsonProperty("qtdeVendida")
	@JsonSerialize(using = BigDecimal8Serializer.class)
	protected BigDecimal qtdeVendida;
	
	protected int contadorRegistroInterno;
	
	
    
	public int getContadorRegistroInterno() {
		return contadorRegistroInterno;
	}
	public void setContadorRegistroInterno(int contadorRegistroInterno) {
		this.contadorRegistroInterno = contadorRegistroInterno;
	}
	/**        
	 * Gets / sets the PK value
	 */
	@JsonProperty("PK")
	public Long getPk() {
		return pk;
	}
	public void setPk(Long value) {
		this.pk = value;
	}
	public Long getCodigoPBM() {
		return codigoPBM;
	}
	public void setCodigoPBM(Long codigoPBM) {
		this.codigoPBM = codigoPBM;
	}
	public BigDecimal getValorPBM() {
		return valorPBM;
	}
	public void setValorPBM(BigDecimal valorPBM) {
		this.valorPBM = valorPBM;
	}
	public Long getNumeroPreVendaPBM() {
		return numeroPreVendaPBM;
	}
	public void setNumeroPreVendaPBM(Long numeroPreVendaPBM) {
		this.numeroPreVendaPBM = numeroPreVendaPBM;
	}
	public Long getNumeroPedidoPBM() {
		return numeroPedidoPBM;
	}
	public void setNumeroPedidoPBM(Long numeroPedidoPBM) {
		this.numeroPedidoPBM = numeroPedidoPBM;
	}
	public String getHoraMinutoEvento() {
		return horaMinutoEvento;
	}
	public void setHoraMinutoEvento(String horaMinutoEvento) {
		this.horaMinutoEvento = horaMinutoEvento;
	}
	public int getCodigoTransacaoInterno() {
		return codigoTransacaoInterno;
	}
	public void setCodigoTransacaoInterno(int codigoTransacaoInterno) {
		this.codigoTransacaoInterno = codigoTransacaoInterno;
	}
	public Long getCodigoAutorizacaoPBM() {
		return codigoAutorizacaoPBM;
	}
	public void setCodigoAutorizacaoPBM(Long codigoAutorizacaoPBM) {
		this.codigoAutorizacaoPBM = codigoAutorizacaoPBM;
	}
	public Long getCodigoRMSProduto() {
		return codigoRMSProduto;
	}
	public void setCodigoRMSProduto(Long codigoRMSProduto) {
		this.codigoRMSProduto = codigoRMSProduto;
	}
	public BigDecimal getQtdeVendida() {
		return qtdeVendida;
	}
	public void setQtdeVendida(BigDecimal qtdeVendida) {
		this.qtdeVendida = qtdeVendida;
	}
	
	@Override
	public String toString() {
		return "TipoDrogariaTransacaoType [codigoPBM=" + codigoPBM + ", valorPBM=" + valorPBM + ", numeroPreVendaPBM="
				+ numeroPreVendaPBM + ", codigoAutorizacaoPBM=" + codigoAutorizacaoPBM + ", numeroPedidoPBM="
				+ numeroPedidoPBM + ", horaMinutoEvento=" + horaMinutoEvento + ", pk=" + pk
				+ ", codigoTransacaoInterno=" + codigoTransacaoInterno + ", codigoRMSProduto=" + codigoRMSProduto
				+ ", qtdeVendida=" + qtdeVendida + "]";
	}

	
	
}
