//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.11 at 03:35:05 PM BRST 
//


package com.dieboldnixdorf.frentecaixa.domain;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;



@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TipoCombustiveisTransacaoType", propOrder = {
    "combustivel"
})
public class TipoCombustiveisTransacaoType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected List<TipoCombustivelTransacaoType> combustivel;
    
    
	public List<TipoCombustivelTransacaoType> getCombustivel() {
        if (combustivel == null) {
        	combustivel = new ArrayList<TipoCombustivelTransacaoType>();
        }
		return combustivel;
	}
	public void setCombustivel(List<TipoCombustivelTransacaoType> combustivel) {
		this.combustivel = combustivel;
	}
	
	@Override
	public String toString() {
		return "TipoCombustiveisTransacaoType [combustivel=" + combustivel + "]";
	}

}
