//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.08 at 02:15:33 PM BRT 
//


package com.dieboldnixdorf.frentecaixa.domain;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;


/**
 * <p>Java class for TipoLocalVendaType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TipoLocalVendaType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="codigoLoja"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
 *               &lt;maxExclusive value="9999"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="numeroCupomFiscal"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
 *               &lt;maxExclusive value="999999"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="transacaoLoja"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
 *               &lt;maxExclusive value="99999"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="codigoTerminalVenda"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
 *               &lt;maxExclusive value="999"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="dataVenda" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="DadosCabecalhoTransacao" type="{http://www.dieboldnixdorf.com/frentecaixa/CabecalhoTransacoesPDV}CabecalhoTransacoesPDVType" maxOccurs="unbounded"/&gt;
 *         &lt;element name="DadosItensTransacao" type="{http://www.dieboldnixdorf.com/frentecaixa/TipoItensTransacao}TipoItensTransacaoType" maxOccurs="unbounded"/&gt;
 *         &lt;element name="DadosPagamentosTransacao" type="{http://www.dieboldnixdorf.com/frentecaixa/TipoPagamentosTransacao}TipoPagamentosTransacaoType" maxOccurs="unbounded"/&gt;
 *         &lt;element name="DadosRodapeTransacao" type="{http://www.dieboldnixdorf.com/frentecaixa/TransacoesPDVRodape}TransacoesPDVRodapeType" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TipoLocalVendaType", propOrder = {
    "codigoLoja",
    "numeroDocumentoFiscal",
    "serieDocumentoFiscal",
    "numeroDANFE",
    "transacaoLoja",
    "codigoTerminalVenda",
    "DRTOperador",
    "siglaLoja",
    "nomeOperador",
    "perfilOperador",
    "NaturezaOperacao",
    "TipoEmissao",
    "CodigoPreOrder",
    "TipoSaida",
    "codigoParceiro",
    "nomeParceiro",
    "barcodePedido",
    "TipoPDV",
    "PK",
    "dataVenda",
    "dadosCabecalhoTransacao",
    "dadosItensTransacao",
    "dadosPagamentosTransacao",
    "dadosCombustivelTransacao",
    "dadosDrogariaTransacao",
    "dadosServicoTransacao",
    "dadosRodapeTransacao"
})
@JsonPropertyOrder({ 
    "codigoLoja",
    "numeroDocumentoFiscal",
    "serieDocumentoFiscal",
    "numeroDANFE",
    "transacaoLoja",
    "codigoTerminalVenda",
    "DRTOperador",
    "siglaLoja",
    "nomeOperador",
    "perfilOperador",
    "NaturezaOperacao",
    "TipoEmissao",
    "CodigoPreOrder",
    "TipoSaida",
    "codigoParceiro",
    "nomeParceiro",
    "barcodePedido",
    "TipoPDV",
    "PK",
    "dataVenda",
    "dadosCabecalhoTransacao",
    "dadosItensTransacao",
    "dadosPagamentosTransacao",
    "dadosCombustivelTransacao",
    "dadosDrogariaTransacao",
    "dadosServicoTransacao",
    "dadosRodapeTransacao"
})
public class TipoLocalVendaType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    protected int codigoLoja;
    protected Long numeroDocumentoFiscal;
    protected int serieDocumentoFiscal;
    protected String numeroDANFE;
    protected int transacaoLoja;
    protected int codigoTerminalVenda;
    protected int DRTOperador;
    protected String siglaLoja;
    protected String nomeOperador;
    protected int perfilOperador;
    protected String NaturezaOperacao;
    protected String TipoEmissao;
    protected String CodigoPreOrder;
    protected int TipoSaida;
    protected int codigoParceiro;
    protected String nomeParceiro;
    protected String barcodePedido;
	protected int TipoPDV;
    protected int PK;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    @JsonProperty("dataVenda")
    @JsonSerialize(using = DataVendaSerializer.class)
    protected Calendar dataVenda;
    @XmlElement(name = "dadosCabecalhoTransacao", required = true)
    protected List<CabecalhoTransacoesPDVType> dadosCabecalhoTransacao;
    @XmlElement(name = "dadosItensTransacao", required = true)
    protected List<TipoItensTransacaoType> dadosItensTransacao;
    @XmlElement(name = "dadosPagamentosTransacao", required = true)
    protected List<TipoPagamentosTransacaoType> dadosPagamentosTransacao;
    
    @XmlElement(name = "dadosCombustivelTransacao", required = true)
    protected List<TipoCombustiveisTransacaoType> dadosCombustivelTransacao;
    
    @XmlElement(name = "dadosDrogariaTransacao", required = true)
    protected List<TipoDrogariasTransacaoType> dadosDrogariaTransacao;
    
    @XmlElement(name = "dadosServicoTransacao", required = true)
    protected List<TipoServicosTransacaoType> dadosServicoTransacao;
    
    @XmlElement(name = "dadosRodapeTransacao", required = true)
    protected List<TransacoesPDVRodapeType> dadosRodapeTransacao;

    public List<TipoServicosTransacaoType> getDadosServicoTransacao() {
        if (dadosServicoTransacao == null) {
        	dadosServicoTransacao = new ArrayList<TipoServicosTransacaoType>();
        }
        
		return dadosServicoTransacao;
	}
    
    public List<TipoCombustiveisTransacaoType> getDadosCombustivelTransacao() {
        if (dadosCombustivelTransacao == null) {
        	dadosCombustivelTransacao = new ArrayList<TipoCombustiveisTransacaoType>();
        }
        
		return dadosCombustivelTransacao;
	}
    
    public List<TipoDrogariasTransacaoType> getDadosDrogariaTransacao() {
        if (dadosDrogariaTransacao == null) {
        	dadosDrogariaTransacao = new ArrayList<TipoDrogariasTransacaoType>();
        }
        
		return dadosDrogariaTransacao;
	}

	public void setDadosCombustivelTransacao(List<TipoCombustiveisTransacaoType> dadosCombustivelTransacao) {
		this.dadosCombustivelTransacao = dadosCombustivelTransacao;
	}

	public String getSiglaLoja() {
		return siglaLoja;
	}

	public void setSiglaLoja(String siglaLoja) {
		this.siglaLoja = siglaLoja;
	}

	public String getNomeOperador() {
		return nomeOperador;
	}

	public void setNomeOperador(String nomeOperador) {
		this.nomeOperador = nomeOperador;
	}

	public int getPerfilOperador() {
		return perfilOperador;
	}

	public void setPerfilOperador(int perfilOperador) {
		this.perfilOperador = perfilOperador;
	}

	public int getCodigoParceiro() {
		return codigoParceiro;
	}

	public void setCodigoParceiro(int codigoParceiro) {
		this.codigoParceiro = codigoParceiro;
	}

	public String getNomeParceiro() {
		return nomeParceiro;
	}

	public void setNomeParceiro(String nomeParceiro) {
		this.nomeParceiro = nomeParceiro;
	}

	public String getBarcodePedido() {
		return barcodePedido;
	}

	public void setBarcodePedido(String barcodePedido) {
		this.barcodePedido = barcodePedido;
	}

    /**
     * Gets the value of the codigoLoja property.
     * 
     */
    public int getCodigoLoja() {
        return codigoLoja;
    }

    /**
     * Sets the value of the codigoLoja property.
     * 
     */
    public void setCodigoLoja(int value) {
        this.codigoLoja = value;
    }

    /**
     * Gets the value of the numeroDocumentoFiscal property.
     * 
     */
    public Long getNumeroDocumentoFiscal() {
        return numeroDocumentoFiscal;
    }

    /**
     * Sets the value of the numeroDocumentoFiscal property.
     * 
     */
    public void setNumeroDocumentoFiscal(Long value) {
        this.numeroDocumentoFiscal = value;
    }

    /**
     * Gets the value of the serieDocumentoFiscal property.
     * 
     */
    public int getSerieDocumentoFiscal() {
		return serieDocumentoFiscal;
	}

    /**
     * Sets the value of the serieDocumentoFiscal property.
     * 
     */
	public void setSerieDocumentoFiscal(int serieDocumentoFiscal) {
		this.serieDocumentoFiscal = serieDocumentoFiscal;
	}

    /**
     * Gets the value of the numeroDANFE property.
     * 
     */
	public String getNumeroDANFE() {
		return numeroDANFE;
	}

    /**
     * Sets the value of the numeroDANFE property.
     * 
     */
	public void setNumeroDANFE(String numeroDANFE) {
		this.numeroDANFE = numeroDANFE;
	}

	/**
     * Gets the value of the transacaoLoja property.
     * 
     */
    public int getTransacaoLoja() {
        return transacaoLoja;
    }

    /**
     * Sets the value of the transacaoLoja property.
     * 
     */
    public void setTransacaoLoja(int value) {
        this.transacaoLoja = value;
    }

    /**
     * Gets the value of the codigoTerminalVenda property.
     * 
     */
    public int getCodigoTerminalVenda() {
        return codigoTerminalVenda;
    }

    /**
     * Sets the value of the codigoTerminalVenda property.
     * 
     */
    public void setCodigoTerminalVenda(int value) {
        this.codigoTerminalVenda = value;
    }

    /**
     * Gets / sets the values of the DRTOperador
     */
    @JsonProperty("DRTOperador")
    public int getDrtOperador() {
        return DRTOperador;
    }
    public void setDrtOperador(int value) {
        this.DRTOperador = value;
    }

    /**
     * Gets / sets the values of the NaturezaOperacao
     */
    @JsonProperty("NaturezaOperacao")
    public String getNaturezaOperacao() {
        return NaturezaOperacao;
    }
    public void setNaturezaOperacao(String value) {
        this.NaturezaOperacao = value;
    }

    /**
     * Gets / sets the values of the TipoEmissao
     */
    @JsonProperty("TipoEmissao")
    public String getTipoEmissao() {
        return TipoEmissao;
    }
    public void setTipoEmissao(String value) {
        this.TipoEmissao = value;
    }

    /**
     * Gets / sets the values of the CodigoPreOrder
     */
    @JsonProperty("CodigoPreOrder")
    public String getCodigoPreOrder() {
        return CodigoPreOrder;
    }
    public void setCodigoPreOrder (String value) {
        this.CodigoPreOrder = value;
    }

    /**
     * Gets / sets the values of the TipoSaida
     */
    @JsonProperty("TipoSaida")
    public int getTipoSaida() {
        return TipoSaida;
    }
    public void setTipoSaida(int value) {
        this.TipoSaida = value;
    }

    /**
     * Gets / sets the values of the TipoPDV
     */
    @JsonProperty("TipoPDV")
    public int getTipoPdv() {
        return TipoPDV;
    }
    public void setTipoPdv(int value) {
        this.TipoPDV = value;
    }

    /**
     * Gets / sets the values of the PK
     */
    @JsonProperty("PK")
    public int getPk() {
        return PK;
    }
    public void setPk(int value) {
        this.PK = value;
    }

    /**
     * Gets the value of the dataVenda property.
     * 
     * @return
     *     possible object is
     *     {@link Calendar }
     *     
     */
    public Calendar getDataVenda() {
        return dataVenda;
    }

    /**
     * Sets the value of the dataVenda property.
     * 
     * @param value
     *     allowed object is
     *     {@link Calendar }
     *     
     */
    public void setDataVenda(Calendar value) {
        this.dataVenda = value;
    }

    /**
     * Gets the value of the dadosCabecalhoTransacao property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dadosCabecalhoTransacao property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDadosCabecalhoTransacao().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CabecalhoTransacoesPDVType }
     * 
     * 
     */
    public List<CabecalhoTransacoesPDVType> getDadosCabecalhoTransacao() {
        if (dadosCabecalhoTransacao == null) {
            dadosCabecalhoTransacao = new ArrayList<CabecalhoTransacoesPDVType>();
        }
        return this.dadosCabecalhoTransacao;
    }

    /**
     * Gets the value of the dadosItensTransacao property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dadosItensTransacao property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDadosItensTransacao().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TipoItensTransacaoType }
     * 
     * 
     */
    public List<TipoItensTransacaoType> getDadosItensTransacao() {
        if (dadosItensTransacao == null) {
            dadosItensTransacao = new ArrayList<TipoItensTransacaoType>();
        }
        return this.dadosItensTransacao;
    }

    /**
     * Gets the value of the dadosPagamentosTransacao property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dadosPagamentosTransacao property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDadosPagamentosTransacao().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TipoPagamentosTransacaoType }
     * 
     * 
     */
    public List<TipoPagamentosTransacaoType> getDadosPagamentosTransacao() {
        if (dadosPagamentosTransacao == null) {
            dadosPagamentosTransacao = new ArrayList<TipoPagamentosTransacaoType>();
        }
        return this.dadosPagamentosTransacao;
    }

    /**
     * Gets the value of the dadosRodapeTransacao property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dadosRodapeTransacao property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDadosRodapeTransacao().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TransacoesPDVRodapeType }
     * 
     * 
     */
    public List<TransacoesPDVRodapeType> getDadosRodapeTransacao() {
        if (dadosRodapeTransacao == null) {
            dadosRodapeTransacao = new ArrayList<TransacoesPDVRodapeType>();
        }
        return this.dadosRodapeTransacao;
    }

}
