//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.11 at 03:35:05 PM BRST 
//


package com.dieboldnixdorf.frentecaixa.domain;

import java.io.Serializable;
import java.math.BigDecimal;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TipoCombustivelTransacaoType", propOrder = {
    "codigoTransacaoInterno",
    "contadorRegistroInterno",
    "PK",
    "codRMSProduto",
    "qtdeVendida",
    "valorEncerranteInicial",
    "valorEncerranteFinal",
    "IDAbastecimento",
    "numeroBicoAbastecimento",
    "numeroBombaAbastecimento",
    "numeroTanqueAbastecimento",
    "horaMinutoEvento"
})
@JsonPropertyOrder({ 
    "codigoTransacaoInterno",
    "contadorRegistroInterno",
    "PK",
    "codRMSProduto",
    "qtdeVendida",
    "valorEncerranteInicial",
    "valorEncerranteFinal",
    "IDAbastecimento",
    "numeroBicoAbastecimento",
    "numeroBombaAbastecimento",
    "numeroTanqueAbastecimento",
    "horaMinutoEvento"
})
public class TipoCombustivelTransacaoType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    
    
    protected Long codRMSProduto;
    
    @JsonProperty("qtdeVendida")
    @JsonSerialize(using = BigDecimal8Serializer.class)
    protected BigDecimal qtdeVendida;

    protected String valorEncerranteInicial;
    
    protected String valorEncerranteFinal;
    
    protected Long IDAbastecimento;
    
    
    protected int numeroBicoAbastecimento;
    protected int numeroBombaAbastecimento;
    protected int numeroTanqueAbastecimento;

    
    @XmlElement(required = true)
    protected String horaMinutoEvento;
    protected Long pk;
    protected int codigoTransacaoInterno;
    
    protected int contadorRegistroInterno;
    
    
    
	public int getContadorRegistroInterno() {
		return contadorRegistroInterno;
	}
	public void setContadorRegistroInterno(int contadorRegistroInterno) {
		this.contadorRegistroInterno = contadorRegistroInterno;
	}
	/**        
	 * Gets / sets the PK value
	 */
	@JsonProperty("PK")
	public Long getPk() {
		return pk;
	}
	public void setPk(Long value) {
		this.pk = value;
	}
	public BigDecimal getQtdeVendida() {
		return qtdeVendida;
	}
	public void setQtdeVendida(BigDecimal qtdeVendida) {
		this.qtdeVendida = qtdeVendida;
	}
	public String getValorEncerranteInicial() {
		return valorEncerranteInicial;
	}
	public void setValorEncerranteInicial(String valorEncerranteInicial) {
		this.valorEncerranteInicial = valorEncerranteInicial;
	}
	public String getValorEncerranteFinal() {
		return valorEncerranteFinal;
	}
	public void setValorEncerranteFinal(String valorEncerranteFinal) {
		this.valorEncerranteFinal = valorEncerranteFinal;
	}
	public int getNumeroBicoAbastecimento() {
		return numeroBicoAbastecimento;
	}
	public void setNumeroBicoAbastecimento(int numeroBicoAbastecimento) {
		this.numeroBicoAbastecimento = numeroBicoAbastecimento;
	}
	public int getNumeroBombaAbastecimento() {
		return numeroBombaAbastecimento;
	}
	public void setNumeroBombaAbastecimento(int numeroBombaAbastecimento) {
		this.numeroBombaAbastecimento = numeroBombaAbastecimento;
	}
	public int getNumeroTanqueAbastecimento() {
		return numeroTanqueAbastecimento;
	}
	public void setNumeroTanqueAbastecimento(int numeroTanqueAbastecimento) {
		this.numeroTanqueAbastecimento = numeroTanqueAbastecimento;
	}
	public String getHoraMinutoEvento() {
		return horaMinutoEvento;
	}
	public void setHoraMinutoEvento(String horaMinutoEvento) {
		this.horaMinutoEvento = horaMinutoEvento;
	}
	public int getCodigoTransacaoInterno() {
		return codigoTransacaoInterno;
	}
	public void setCodigoTransacaoInterno(int codigoTransacaoInterno) {
		this.codigoTransacaoInterno = codigoTransacaoInterno;
	}
	public Long getCodRMSProduto() {
		return codRMSProduto;
	}
	public void setCodRMSProduto(Long codRMSProduto) {
		this.codRMSProduto = codRMSProduto;
	}
	public Long getIDAbastecimento() {
		return IDAbastecimento;
	}
	public void setIDAbastecimento(Long iDAbastecimento) {
		IDAbastecimento = iDAbastecimento;
	}
	@Override
	public String toString() {
		return "TipoCombustivelTransacaoType [codRMSProduto=" + codRMSProduto + ", qtdeVendida=" + qtdeVendida
				+ ", valorEncerranteInicial=" + valorEncerranteInicial + ", valorEncerranteFinal="
				+ valorEncerranteFinal + ", IDAbastecimento=" + IDAbastecimento + ", numeroBicoAbastecimento="
				+ numeroBicoAbastecimento + ", numeroBombaAbastecimento=" + numeroBombaAbastecimento
				+ ", numeroTanqueAbastecimento=" + numeroTanqueAbastecimento + ", horaMinutoEvento=" + horaMinutoEvento
				+ ", pk=" + pk + ", codigoTransacaoInterno=" + codigoTransacaoInterno + "]";
	}

	

}
