//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.08 at 02:15:33 PM BRT 
//


package com.dieboldnixdorf.frentecaixa.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;


/**
 * <p>Java class for TransacoesPDVPayloadType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TransacoesPDVPayloadType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="codigoTransacaoInterno"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
 *               &lt;enumeration value="20"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="tipoCupomFiscal"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="00"/&gt;
 *               &lt;enumeration value="01"/&gt;
 *               &lt;enumeration value="02"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="contadorRegistroInterno"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
 *               &lt;maxExclusive value="999"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="codigoRMSProduto"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="13"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="EANProduto"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="13"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="valorTotalItemTributado" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="valorTotalItemSemTributacao" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="quantidadeItensVendidos" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="precoUnitarioLiquidoItem" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="tipoDesconto" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="01"/&gt;
 *               &lt;enumeration value="02"/&gt;
 *               &lt;enumeration value="03"/&gt;
 *               &lt;enumeration value="04"/&gt;
 *               &lt;enumeration value="05"/&gt;
 *               &lt;enumeration value="06"/&gt;
 *               &lt;enumeration value="07"/&gt;
 *               &lt;enumeration value="99"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="valorTotalDesconto" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="precoUnitarioBrutoItem" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="codigoSetorItem" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
 *               &lt;maxExclusive value="999"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="horaMinutoEvento"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="4"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TransacoesPDVPayloadType", propOrder = {
    "codigoTransacaoInterno",
    "PK",
    "tipoCupomFiscal",
    "contadorRegistroInterno",
    "codigoRMSProduto",
    "eanProduto",
    "imeiProduto",
    "valorTotalItemTributado",
    "valorTotalItemSemTributacao",
    "quantidadeItensVendidos",
    "precoUnitarioLiquidoItem",
    "tipoDesconto",
    "valorTotalDesconto",
    "precoUnitarioBrutoItem",
    "codigoSetorItem",
    "valorTotalTEFPromocao",
    "valorTotalItemICMS",
    "valorTotalItemBaseCalcPIS",
    "valorTotalItemBaseCalcCOFINS",
    "valorTotalItemPIS",
    "valorTotalItemCOFINS",
    "valorPercentualAliquotaFiscal",
    "aliquotaFCP",
    "valorFCP",
    "valorBaseCalcSTRetido",
    "aliquotaConsumidorFinal",
    "valorSTRetido",
    "valorBaseCalcFCPSTRetido",
    "percFCPSTRetido",
    "percRedBaseCalcEfet",
    "valorBaseCalcEfet",
    "aliquotaICMSEfet",
    "valorICMSEfet",
    "aliquotaISS",
    "aliquotaIPI",
    "aliquotaImpostoMunicipal",
    "aliquotaImpostoEstadual",
    "aliquotaImpostoFederal",
    "valorISS",
    "valorIPI",
    "aliquotaPIS",
    "aliquotaCOFINS",
    "valorImpostoMunicipal",
    "valorImpostoEstadual",
    "valorImpostoFederal",
    "codigoCSTICMS",
    "aliquotaICMSDeson",
    "valorREDBaseCalcDeson",
    "motivoDeson",
    "valorICMSDeson",
    "horaMinutoEvento"
})
@JsonPropertyOrder({ 
    "codigoTransacaoInterno",
    "PK",
    "tipoCupomFiscal",
    "contadorRegistroInterno",
    "codigoRMSProduto",
    "eanProduto",
    "imeiProduto",
    "valorTotalItemTributado",
    "valorTotalItemSemTributacao",
    "quantidadeItensVendidos",
    "precoUnitarioLiquidoItem",
    "tipoDesconto",
    "valorTotalDesconto",
    "precoUnitarioBrutoItem",
    "codigoSetorItem",
    "valorTotalTEFPromocao",
    "valorTotalItemICMS",
    "valorTotalItemBaseCalcPIS",
    "valorTotalItemBaseCalcCOFINS",
    "valorTotalItemPIS",
    "valorTotalItemCOFINS",
    "valorPercentualAliquotaFiscal",
    "aliquotaFCP",
    "valorFCP",
    "valorBaseCalcSTRetido",
    "aliquotaConsumidorFinal",
    "valorSTRetido",
    "valorBaseCalcFCPSTRetido",
    "percFCPSTRetido",
    "percRedBaseCalcEfet",
    "valorBaseCalcEfet",
    "aliquotaICMSEfet",
    "valorICMSEfet",
    "aliquotaISS",
    "aliquotaIPI",
    "aliquotaPIS",
    "aliquotaCOFINS",
    "aliquotaImpostoMunicipal",
    "aliquotaImpostoEstadual",
    "aliquotaImpostoFederal",
    "valorISS",
    "valorIPI",
    "valorImpostoMunicipal",
    "valorImpostoEstadual",
    "valorImpostoFederal",
    "codigoCSTICMS",
    "aliquotaICMSDeson",
    "valorREDBaseCalcDeson",
    "motivoDeson",
    "valorICMSDeson",
    "horaMinutoEvento"
})
public class TransacoesPDVPayloadType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    protected int codigoTransacaoInterno;
    @XmlElement(required = true)
    protected String tipoCupomFiscal;
    protected int contadorRegistroInterno;
    @XmlElement(required = true)
    protected Long codigoRMSProduto;
    @XmlElement(name = "eanProduto", required = true)
    protected Long eanProduto;
    @XmlElement(required = true)
    @JsonProperty("valorTotalItemTributado")
    @JsonSerialize(using = BigDecimal8Serializer.class)
    protected BigDecimal valorTotalItemTributado;
    @XmlElement(required = true)
    @JsonProperty("valorTotalItemSemTributacao")
    @JsonSerialize(using = BigDecimal8Serializer.class)
    protected BigDecimal valorTotalItemSemTributacao;
    @XmlElement(required = true)
    @JsonProperty("quantidadeItensVendidos")
    @JsonSerialize(using = QuantidadeItensVendidosBigDecimalSerializer.class)
    protected BigDecimal quantidadeItensVendidos;
    @XmlElement(required = true)
    @JsonProperty("precoUnitarioLiquidoItem")
    @JsonSerialize(using = BigDecimal9Serializer.class)
    protected BigDecimal precoUnitarioLiquidoItem;
    protected String tipoDesconto;
    @JsonProperty("valorTotalDesconto")
    @JsonSerialize(using = BigDecimal8Serializer.class)
    protected BigDecimal valorTotalDesconto;
    @XmlElement(required = true)
    @JsonProperty("precoUnitarioBrutoItem")
    @JsonSerialize(using = BigDecimal9Serializer.class)
    protected BigDecimal precoUnitarioBrutoItem;
    protected Integer codigoSetorItem;
    
    @XmlElement(required = true)
    @JsonProperty("valorTotalTEFPromocao")
    @JsonSerialize(using = BigDecimal8Serializer.class)
    protected BigDecimal valorTotalTEFPromocao;
    
    @XmlElement(required = true)
    @JsonProperty("valorTotalItemICMS")
    @JsonSerialize(using = BigDecimal8Serializer.class)
    protected BigDecimal valorTotalItemICMS;
    
    @XmlElement(required = true)
    @JsonProperty("valorTotalItemBaseCalcPIS")
    @JsonSerialize(using = BigDecimal8Serializer.class)
    protected BigDecimal valorTotalItemBaseCalcPIS;
    
    @XmlElement(required = true)
    @JsonProperty("valorTotalItemBaseCalcCOFINS")
    @JsonSerialize(using = BigDecimal8Serializer.class)
    protected BigDecimal valorTotalItemBaseCalcCOFINS;
    
    @XmlElement(required = true)
    @JsonProperty("valorTotalItemPIS")
    @JsonSerialize(using = BigDecimal8Serializer.class)
    protected BigDecimal valorTotalItemPIS;
    
    @XmlElement(required = true)
    @JsonProperty("valorTotalItemCOFINS")
    @JsonSerialize(using = BigDecimal8Serializer.class)
    protected BigDecimal valorTotalItemCOFINS;
    
    @XmlElement(required = true)
    @JsonProperty("valorPercentualAliquotaFiscal")
    @JsonSerialize(using = BigDecimal8Serializer.class)
    protected BigDecimal valorPercentualAliquotaFiscal;
    
    @XmlElement(required = true)
    @JsonProperty("aliquotaFCP")
    @JsonSerialize(using = BigDecimal8Serializer.class)
    protected BigDecimal aliquotaFCP;
    
    @XmlElement(required = true)
    @JsonProperty("valorFCP")
    @JsonSerialize(using = BigDecimal8Serializer.class)
    protected BigDecimal valorFCP;
    
    @XmlElement(required = true)
    @JsonProperty("valorBaseCalcSTRetido")
    @JsonSerialize(using = BigDecimal8Serializer.class)
    protected BigDecimal valorBaseCalcSTRetido;
    
    @XmlElement(required = true)
    @JsonProperty("aliquotaConsumidorFinal")
    @JsonSerialize(using = BigDecimal8Serializer.class)
    protected BigDecimal aliquotaConsumidorFinal;
    
    @XmlElement(required = true)
    @JsonProperty("valorSTRetido")
    @JsonSerialize(using = BigDecimal8Serializer.class)
    protected BigDecimal valorSTRetido;
    
    @XmlElement(required = true)
    @JsonProperty("valorBaseCalcFCPSTRetido")
    @JsonSerialize(using = BigDecimal8Serializer.class)
    protected BigDecimal valorBaseCalcFCPSTRetido;
    
    @XmlElement(required = true)
    @JsonProperty("percFCPSTRetido")
    @JsonSerialize(using = BigDecimal8Serializer.class)
    protected BigDecimal percFCPSTRetido;
    
    @XmlElement(required = true)
    @JsonProperty("percRedBaseCalcEfet")
    @JsonSerialize(using = BigDecimal8Serializer.class)
    protected BigDecimal percRedBaseCalcEfet;
    
    @XmlElement(required = true)
    @JsonProperty("valorBaseCalcEfet")
    @JsonSerialize(using = BigDecimal8Serializer.class)
    protected BigDecimal valorBaseCalcEfet;
    
    @XmlElement(required = true)
    @JsonProperty("aliquotaICMSEfet")
    @JsonSerialize(using = BigDecimal8Serializer.class)
    protected BigDecimal aliquotaICMSEfet;
    
    @XmlElement(required = true)
    @JsonProperty("valorICMSEfet")
    @JsonSerialize(using = BigDecimal8Serializer.class)
    protected BigDecimal valorICMSEfet;
    
    @XmlElement(required = true)
    @JsonProperty("aliquotaISS")
    @JsonSerialize(using = BigDecimal8Serializer.class)
    protected BigDecimal aliquotaISS;
    
    @XmlElement(required = true)
    @JsonProperty("aliquotaIPI")
    @JsonSerialize(using = BigDecimal8Serializer.class)
    protected BigDecimal aliquotaIPI;
    
    @XmlElement(required = true)
    @JsonProperty("aliquotaImpostoMunicipal")
    @JsonSerialize(using = BigDecimal8Serializer.class)
    protected BigDecimal aliquotaImpostoMunicipal;
    
    @XmlElement(required = true)
    @JsonProperty("aliquotaImpostoEstadual")
    @JsonSerialize(using = BigDecimal8Serializer.class)
    protected BigDecimal aliquotaImpostoEstadual;
    
    @XmlElement(required = true)
    @JsonProperty("aliquotaImpostoFederal")
    @JsonSerialize(using = BigDecimal8Serializer.class)
    protected BigDecimal aliquotaImpostoFederal;
    
    @XmlElement(required = true)
    @JsonProperty("valorISS")
    @JsonSerialize(using = BigDecimal8Serializer.class)
    protected BigDecimal valorISS;
    
    @XmlElement(required = true)
    @JsonProperty("valorIPI")
    @JsonSerialize(using = BigDecimal8Serializer.class)
    protected BigDecimal valorIPI;
    
    @XmlElement(required = true)
    @JsonProperty("valorImpostoMunicipal")
    @JsonSerialize(using = BigDecimal8Serializer.class)
    protected BigDecimal valorImpostoMunicipal;
    
    @XmlElement(required = true)
    @JsonProperty("valorImpostoEstadual")
    @JsonSerialize(using = BigDecimal8Serializer.class)
    protected BigDecimal valorImpostoEstadual;
    
    @XmlElement(required = true)
    @JsonProperty("valorImpostoFederal")
    @JsonSerialize(using = BigDecimal8Serializer.class)
    protected BigDecimal valorImpostoFederal;

    @XmlElement(required = true)
    @JsonProperty("codigoCSTICMS")
    @JsonSerialize(using = BigDecimal8Serializer.class)
    protected BigDecimal codigoCSTICMS;
    
    @XmlElement(required = true)
    @JsonProperty("aliquotaICMSDeson")
    @JsonSerialize(using = BigDecimal8Serializer.class)
    protected BigDecimal aliquotaICMSDeson;
    
    @XmlElement(required = true)
    @JsonProperty("valorREDBaseCalcDeson")
    @JsonSerialize(using = BigDecimal8Serializer.class)
    protected BigDecimal valorREDBaseCalcDeson;
    
    @XmlElement(required = true)
    @JsonProperty("motivoDeson")
    @JsonSerialize(using = BigDecimal8Serializer.class)
    protected BigDecimal motivoDeson;
    
    @XmlElement(required = true)
    @JsonProperty("valorICMSDeson")
    @JsonSerialize(using = BigDecimal8Serializer.class)
    protected BigDecimal valorICMSDeson;
    
    @XmlElement(required = true)
    @JsonProperty("aliquotaPIS")
    @JsonSerialize(using = BigDecimal8Serializer.class)
    protected BigDecimal aliquotaPIS;
    
    @XmlElement(required = true)
    @JsonProperty("aliquotaCOFINS")
    @JsonSerialize(using = BigDecimal8Serializer.class)
    protected BigDecimal aliquotaCOFINS;
    
    @XmlElement(required = true)
    protected String horaMinutoEvento;

    protected Long pk;
    protected String imeiProduto;

    
    
    public BigDecimal getValorTotalTEFPromocao() {
		return valorTotalTEFPromocao;
	}

	public void setValorTotalTEFPromocao(BigDecimal valorTotalTEFPromocao) {
		this.valorTotalTEFPromocao = valorTotalTEFPromocao;
	}

	public BigDecimal getValorTotalItemICMS() {
		return valorTotalItemICMS;
	}

	public void setValorTotalItemICMS(BigDecimal valorTotalItemICMS) {
		this.valorTotalItemICMS = valorTotalItemICMS;
	}

	public BigDecimal getValorTotalItemBaseCalcPIS() {
		return valorTotalItemBaseCalcPIS;
	}

	public void setValorTotalItemBaseCalcPIS(BigDecimal valorTotalItemBaseCalcPIS) {
		this.valorTotalItemBaseCalcPIS = valorTotalItemBaseCalcPIS;
	}

	public BigDecimal getValorTotalItemBaseCalcCOFINS() {
		return valorTotalItemBaseCalcCOFINS;
	}

	public void setValorTotalItemBaseCalcCOFINS(BigDecimal valorTotalItemBaseCalcCOFINS) {
		this.valorTotalItemBaseCalcCOFINS = valorTotalItemBaseCalcCOFINS;
	}

	public BigDecimal getValorTotalItemPIS() {
		return valorTotalItemPIS;
	}

	public void setValorTotalItemPIS(BigDecimal valorTotalItemPIS) {
		this.valorTotalItemPIS = valorTotalItemPIS;
	}

	public BigDecimal getValorTotalItemCOFINS() {
		return valorTotalItemCOFINS;
	}

	public void setValorTotalItemCOFINS(BigDecimal valorTotalItemCOFINS) {
		this.valorTotalItemCOFINS = valorTotalItemCOFINS;
	}

	public BigDecimal getValorPercentualAliquotaFiscal() {
		return valorPercentualAliquotaFiscal;
	}

	public void setValorPercentualAliquotaFiscal(BigDecimal valorPercentualAliquotaFiscal) {
		this.valorPercentualAliquotaFiscal = valorPercentualAliquotaFiscal;
	}

	public BigDecimal getAliquotaFCP() {
		return aliquotaFCP;
	}

	public void setAliquotaFCP(BigDecimal aliquotaFCP) {
		this.aliquotaFCP = aliquotaFCP;
	}

	public BigDecimal getValorFCP() {
		return valorFCP;
	}

	public void setValorFCP(BigDecimal valorFCP) {
		this.valorFCP = valorFCP;
	}

	public BigDecimal getValorBaseCalcSTRetido() {
		return valorBaseCalcSTRetido;
	}

	public void setValorBaseCalcSTRetido(BigDecimal valorBaseCalcSTRetido) {
		this.valorBaseCalcSTRetido = valorBaseCalcSTRetido;
	}

	public BigDecimal getAliquotaConsumidorFinal() {
		return aliquotaConsumidorFinal;
	}

	public void setAliquotaConsumidorFinal(BigDecimal aliquotaConsumidorFinal) {
		this.aliquotaConsumidorFinal = aliquotaConsumidorFinal;
	}

	public BigDecimal getValorSTRetido() {
		return valorSTRetido;
	}

	public void setValorSTRetido(BigDecimal valorSTRetido) {
		this.valorSTRetido = valorSTRetido;
	}

	public BigDecimal getValorBaseCalcFCPSTRetido() {
		return valorBaseCalcFCPSTRetido;
	}

	public void setValorBaseCalcFCPSTRetido(BigDecimal valorBaseCalcFCPSTRetido) {
		this.valorBaseCalcFCPSTRetido = valorBaseCalcFCPSTRetido;
	}

	public BigDecimal getPercFCPSTRetido() {
		return percFCPSTRetido;
	}

	public void setPercFCPSTRetido(BigDecimal percFCPSTRetido) {
		this.percFCPSTRetido = percFCPSTRetido;
	}

	public BigDecimal getPercRedBaseCalcEfet() {
		return percRedBaseCalcEfet;
	}

	public void setPercRedBaseCalcEfet(BigDecimal percRedBaseCalcEfet) {
		this.percRedBaseCalcEfet = percRedBaseCalcEfet;
	}

	public BigDecimal getValorBaseCalcEfet() {
		return valorBaseCalcEfet;
	}

	public void setValorBaseCalcEfet(BigDecimal valorBaseCalcEfet) {
		this.valorBaseCalcEfet = valorBaseCalcEfet;
	}

	public BigDecimal getAliquotaICMSEfet() {
		return aliquotaICMSEfet;
	}

	public void setAliquotaICMSEfet(BigDecimal aliquotaICMSEfet) {
		this.aliquotaICMSEfet = aliquotaICMSEfet;
	}

	public BigDecimal getValorICMSEfet() {
		return valorICMSEfet;
	}

	public void setValorICMSEfet(BigDecimal valorICMSEfet) {
		this.valorICMSEfet = valorICMSEfet;
	}

	public BigDecimal getAliquotaISS() {
		return aliquotaISS;
	}

	public void setAliquotaISS(BigDecimal aliquotaISS) {
		this.aliquotaISS = aliquotaISS;
	}

	public BigDecimal getAliquotaIPI() {
		return aliquotaIPI;
	}

	public void setAliquotaIPI(BigDecimal aliquotaIPI) {
		this.aliquotaIPI = aliquotaIPI;
	}

	public BigDecimal getAliquotaImpostoMunicipal() {
		return aliquotaImpostoMunicipal;
	}

	public void setAliquotaImpostoMunicipal(BigDecimal aliquotaImpostoMunicipal) {
		this.aliquotaImpostoMunicipal = aliquotaImpostoMunicipal;
	}

	public BigDecimal getAliquotaImpostoEstadual() {
		return aliquotaImpostoEstadual;
	}

	public void setAliquotaImpostoEstadual(BigDecimal aliquotaImpostoEstadual) {
		this.aliquotaImpostoEstadual = aliquotaImpostoEstadual;
	}

	public BigDecimal getAliquotaImpostoFederal() {
		return aliquotaImpostoFederal;
	}

	public void setAliquotaImpostoFederal(BigDecimal aliquotaImpostoFederal) {
		this.aliquotaImpostoFederal = aliquotaImpostoFederal;
	}

	public BigDecimal getValorISS() {
		return valorISS;
	}

	public void setValorISS(BigDecimal valorISS) {
		this.valorISS = valorISS;
	}

	public BigDecimal getValorIPI() {
		return valorIPI;
	}

	public void setValorIPI(BigDecimal valorIPI) {
		this.valorIPI = valorIPI;
	}

	public BigDecimal getValorImpostoMunicipal() {
		return valorImpostoMunicipal;
	}

	public void setValorImpostoMunicipal(BigDecimal valorImpostoMunicipal) {
		this.valorImpostoMunicipal = valorImpostoMunicipal;
	}

	public BigDecimal getValorImpostoEstadual() {
		return valorImpostoEstadual;
	}

	public void setValorImpostoEstadual(BigDecimal valorImpostoEstadual) {
		this.valorImpostoEstadual = valorImpostoEstadual;
	}

	public BigDecimal getValorImpostoFederal() {
		return valorImpostoFederal;
	}

	public void setValorImpostoFederal(BigDecimal valorImpostoFederal) {
		this.valorImpostoFederal = valorImpostoFederal;
	}

	public BigDecimal getCodigoCSTICMS() {
		return codigoCSTICMS;
	}

	public void setCodigoCSTICMS(BigDecimal codigoCSTICMS) {
		this.codigoCSTICMS = codigoCSTICMS;
	}

	public BigDecimal getAliquotaICMSDeson() {
		return aliquotaICMSDeson;
	}

	public void setAliquotaICMSDeson(BigDecimal aliquotaICMSDeson) {
		this.aliquotaICMSDeson = aliquotaICMSDeson;
	}

	public BigDecimal getValorREDBaseCalcDeson() {
		return valorREDBaseCalcDeson;
	}

	public void setValorREDBaseCalcDeson(BigDecimal valorREDBaseCalcDeson) {
		this.valorREDBaseCalcDeson = valorREDBaseCalcDeson;
	}

	public BigDecimal getMotivoDeson() {
		return motivoDeson;
	}

	public void setMotivoDeson(BigDecimal motivoDeson) {
		this.motivoDeson = motivoDeson;
	}

	public BigDecimal getValorICMSDeson() {
		return valorICMSDeson;
	}

	public void setValorICMSDeson(BigDecimal valorICMSDeson) {
		this.valorICMSDeson = valorICMSDeson;
	}

	/**
     * Gets the value of the codigoTransacaoInterno property.
     * 
     */
    public int getCodigoTransacaoInterno() {
        return codigoTransacaoInterno;
    }

    /**
     * Sets the value of the codigoTransacaoInterno property.
     * 
     */
    public void setCodigoTransacaoInterno(int value) {
        this.codigoTransacaoInterno = value;
    }

    /**
     * Gets the value of the tipoCupomFiscal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoCupomFiscal() {
        return tipoCupomFiscal;
    }

    /**
     * Sets the value of the tipoCupomFiscal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoCupomFiscal(String value) {
        this.tipoCupomFiscal = value;
    }

    /**
     * Gets the value of the contadorRegistroInterno property.
     * 
     */
    public int getContadorRegistroInterno() {
        return contadorRegistroInterno;
    }

    /**
     * Sets the value of the contadorRegistroInterno property.
     * 
     */
    public void setContadorRegistroInterno(int value) {
        this.contadorRegistroInterno = value;
    }

    /**
     * Gets the value of the codigoRMSProduto property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getCodigoRMSProduto() {
        return codigoRMSProduto;
    }

    /**
     * Sets the value of the codigoRMSProduto property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setCodigoRMSProduto(Long value) {
        this.codigoRMSProduto = value;
    }

    /**
     * Gets the value of the eanProduto property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getEanProduto() {
        return eanProduto;
    }

    /**
     * Sets the value of the eanProduto property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setEanProduto(Long value) {
        this.eanProduto = value;
    }

    /**
     * Gets the value of the valorTotalItemTributado property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValorTotalItemTributado() {
        return valorTotalItemTributado;
    }

    /**
     * Sets the value of the valorTotalItemTributado property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValorTotalItemTributado(BigDecimal value) {
        this.valorTotalItemTributado = value;
    }

    /**
     * Gets the value of the valorTotalItemSemTributacao property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValorTotalItemSemTributacao() {
        return valorTotalItemSemTributacao;
    }

    /**
     * Sets the value of the valorTotalItemSemTributacao property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValorTotalItemSemTributacao(BigDecimal value) {
        this.valorTotalItemSemTributacao = value;
    }

    /**
     * Gets the value of the quantidadeItensVendidos property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getQuantidadeItensVendidos() {
        return quantidadeItensVendidos;
    }

    /**
     * Sets the value of the quantidadeItensVendidos property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setQuantidadeItensVendidos(BigDecimal value) {
        this.quantidadeItensVendidos = value;
    }

    /**
     * Gets the value of the precoUnitarioLiquidoItem property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPrecoUnitarioLiquidoItem() {
        return precoUnitarioLiquidoItem;
    }

    /**
     * Sets the value of the precoUnitarioLiquidoItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPrecoUnitarioLiquidoItem(BigDecimal value) {
        this.precoUnitarioLiquidoItem = value;
    }

    /**
     * Gets the value of the tipoDesconto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoDesconto() {
        return tipoDesconto;
    }

    /**
     * Sets the value of the tipoDesconto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoDesconto(String value) {
        this.tipoDesconto = value;
    }

    /**
     * Gets the value of the valorTotalDesconto property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValorTotalDesconto() {
        return valorTotalDesconto;
    }

    /**
     * Sets the value of the valorTotalDesconto property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValorTotalDesconto(BigDecimal value) {
        this.valorTotalDesconto = value;
    }

    /**
     * Gets the value of the precoUnitarioBrutoItem property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPrecoUnitarioBrutoItem() {
        return precoUnitarioBrutoItem;
    }

    /**
     * Sets the value of the precoUnitarioBrutoItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPrecoUnitarioBrutoItem(BigDecimal value) {
        this.precoUnitarioBrutoItem = value;
    }

    /**
     * Gets the value of the codigoSetorItem property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCodigoSetorItem() {
        return codigoSetorItem;
    }

    /**
     * Sets the value of the codigoSetorItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCodigoSetorItem(Integer value) {
        this.codigoSetorItem = value;
    }

    /**
     * Gets the value of the horaMinutoEvento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHoraMinutoEvento() {
        return horaMinutoEvento;
    }

    /**
     * Sets the value of the horaMinutoEvento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHoraMinutoEvento(String value) {
        this.horaMinutoEvento = value;
    }

	/**
	 * Gets / set the imeiProduto
	 */
	@JsonProperty("imeiProduto")
	public String getImeiProduto() {
		return imeiProduto;
	}
	public void setImeiProduto(String value) {
		this.imeiProduto = value;
	}

	/**
	 * Gets / set the PK
	 */
	@JsonProperty("PK")
	public Long getPk() {
		return pk;
	}
	public void setPk(Long value) {
		this.pk = value;
	}

	public BigDecimal getAliquotaPIS() {
		return aliquotaPIS;
	}

	public void setAliquotaPIS(BigDecimal aliquotaPIS) {
		this.aliquotaPIS = aliquotaPIS;
	}

	public BigDecimal getAliquotaCOFINS() {
		return aliquotaCOFINS;
	}

	public void setAliquotaCOFINS(BigDecimal aliquotaCOFINS) {
		this.aliquotaCOFINS = aliquotaCOFINS;
	}
	
	



}
