//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.11 at 06:03:02 PM BRT 
//


package com.dieboldnixdorf.frentecaixa.domain;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.dieboldnixdorf.frentecaixa.domain.CodigoLojaType;
import com.dieboldnixdorf.frentecaixa.domain.DataExtracaoType;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * <p>Java class for CabecalhoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CabecalhoType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="codigoLoja" type="{http://www.dieboldnixdorf.com/frentecaixa/TipoCodigoLoja}CodigoLojaType"/&gt;
 *         &lt;element name="dataExtracao" type="{http://www.dieboldnixdorf.com/frentecaixa/TipoDataExtracao}DataExtracaoType"/&gt;
 *         &lt;element name="totalRegistros" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="totalPaginas" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="totalRegistrosPorPagina" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CabecalhoType", propOrder = {
    "codigoLoja",
    "dataExtracao",
    "totalRegistros",
    "totalPaginas",
    "totalRegistrosPorPagina"
})
@JsonPropertyOrder({ 
    "codigoLoja",
    "dataExtracao",
    "totalRegistros",
    "totalPaginas",
    "totalRegistrosPorPagina"
})
public class CabecalhoType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected CodigoLojaType codigoLoja;
    @XmlElement(required = true)
    protected DataExtracaoType dataExtracao;
    protected Long totalRegistros;
    protected Long totalPaginas;
    protected Long totalRegistrosPorPagina;

    /**
     * Gets the value of the codigoLoja property.
     * 
     * @return
     *     possible object is
     *     {@link CodigoLojaType }
     *     
     */
    public CodigoLojaType getCodigoLoja() {
        return codigoLoja;
    }

    /**
     * Sets the value of the codigoLoja property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodigoLojaType }
     *     
     */
    public void setCodigoLoja(CodigoLojaType value) {
        this.codigoLoja = value;
    }

    /**
     * Gets the value of the dataExtracao property.
     * 
     * @return
     *     possible object is
     *     {@link DataExtracaoType }
     *     
     */
    public DataExtracaoType getDataExtracao() {
        return dataExtracao;
    }

    /**
     * Sets the value of the dataExtracao property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataExtracaoType }
     *     
     */
    public void setDataExtracao(DataExtracaoType value) {
        this.dataExtracao = value;
    }

    /**
     * Gets the value of the totalRegistros property.
     * 
     */
    public Long getTotalRegistros() {
        return totalRegistros;
    }

    /**
     * Sets the value of the totalRegistros property.
     * 
     */
    public void setTotalRegistros(Long value) {
        this.totalRegistros = value;
    }

    /**
     * Gets the value of the totalPaginas property.
     * 
     */
    public Long getTotalPaginas() {
        return totalPaginas;
    }

    /**
     * Sets the value of the totalPaginas property.
     * 
     */
    public void setTotalPaginas(Long value) {
        this.totalPaginas = value;
    }

    /**
     * Gets the value of the totalRegistrosPorPagina property.
     * 
     */
    public Long getTotalRegistrosPorPagina() {
        return totalRegistrosPorPagina;
    }

    /**
     * Sets the value of the totalRegistrosPorPagina property.
     * 
     */
    public void setTotalRegistrosPorPagina(Long value) {
        this.totalRegistrosPorPagina = value;
    }

}
