//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.11 at 03:35:05 PM BRST 
//


package com.dieboldnixdorf.frentecaixa.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;


/**
 * <p>Java class for TrasacoesECFPayloadType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TrasacoesECFPayloadType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="numeroECF" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="contadorReducoes"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
 *               &lt;maxExclusive value="999999"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="numeroOperacaoInicial"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
 *               &lt;maxExclusive value="999999"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="numeroOperacaoFinal"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
 *               &lt;maxExclusive value="999999"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="movimentoTotalBrutoDia" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="valorTotalCancelados" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="valorTotalDescontos" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="valorContabil" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="GTInicial" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="GTFinal" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="quantidadeClientes"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}long"&gt;
 *               &lt;maxExclusive value="9999999999"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="acumuladorIsento" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="acumuladorNaoTributado" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="acumuladorSubstituicaoTributaria" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="contadorReinicioOperacao"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
 *               &lt;maxExclusive value="999"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TransacoesECFPayloadType", propOrder = {
    "numeroECF",
    "contadorReducoes",
    "numeroOperacaoInicial",
    "numeroOperacaoFinal",
    "movimentoTotalBrutoDia",
    "valorTotalCancelados",
    "valorTotalDescontos",
    "valorContabil",
    "gtInicial",
    "gtFinal",
    "quantidadeClientes",
    "acumuladorIsento",
    "acumuladorNaoTributado",
    "acumuladorSubstituicaoTributaria",
    "contadorReinicioOperacao",
    "indicadorECFPeriferico"
})
@JsonPropertyOrder({ 
    "numeroECF",
    "contadorReducoes",
    "numeroOperacaoInicial",
    "numeroOperacaoFinal",
    "movimentoTotalBrutoDia",
    "valorTotalCancelados",
    "valorTotalDescontos",
    "valorContabil",
    "gtInicial",
    "gtFinal",
    "quantidadeClientes",
    "acumuladorIsento",
    "acumuladorNaoTributado",
    "acumuladorSubstituicaoTributaria",
    "contadorReinicioOperacao",
    "indicadorECFPeriferico"
})
public class TransacoesECFPayloadType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    protected int numeroECF;
    protected int contadorReducoes;
    protected int numeroOperacaoInicial;
    protected int numeroOperacaoFinal;
    @XmlElement(required = true)
    @JsonProperty("movimentoTotalBrutoDia")
    @JsonSerialize(using = BigDecimalSerializer.class)
    protected BigDecimal movimentoTotalBrutoDia;
    @XmlElement(required = true)
    @JsonProperty("valorTotalCancelados")
    @JsonSerialize(using = BigDecimalSerializer.class)
    protected BigDecimal valorTotalCancelados;
    @XmlElement(required = true)
    @JsonProperty("valorTotalDescontos")
    @JsonSerialize(using = BigDecimalSerializer.class)
    protected BigDecimal valorTotalDescontos;
    @XmlElement(required = true)
    @JsonProperty("valorContabil")
    @JsonSerialize(using = BigDecimalSerializer.class)
    protected BigDecimal valorContabil;
    @XmlElement(required = true)
    @JsonProperty("gtInicial")
    @JsonSerialize(using = BigDecimalSerializer.class)
    protected BigDecimal gtInicial;
    @XmlElement(required = true)
    @JsonProperty("gtFinal")
    @JsonSerialize(using = BigDecimalSerializer.class)
    protected BigDecimal gtFinal;
    protected long quantidadeClientes;
    @XmlElement(required = true)
    @JsonProperty("acumuladorIsento")
    @JsonSerialize(using = BigDecimalSerializer.class)
    protected BigDecimal acumuladorIsento;
    @XmlElement(required = true)
    @JsonProperty("acumuladorNaoTributado")
    @JsonSerialize(using = BigDecimalSerializer.class)
    protected BigDecimal acumuladorNaoTributado;
    @XmlElement(required = true)
    @JsonProperty("acumuladorSubstituicaoTributaria")
    @JsonSerialize(using = BigDecimalSerializer.class)
    protected BigDecimal acumuladorSubstituicaoTributaria;
    protected int contadorReinicioOperacao;
    @XmlElement(required = true)
    protected String indicadorECFPeriferico;

    /**
     * Gets the value of the numeroECF property.
     * 
     */
    public int getNumeroECF() {
        return numeroECF;
    }

    /**
     * Sets the value of the numeroECF property.
     * 
     */
    public void setNumeroECF(int value) {
        this.numeroECF = value;
    }

    /**
     * Gets the value of the contadorReducoes property.
     * 
     */
    public int getContadorReducoes() {
        return contadorReducoes;
    }

    /**
     * Sets the value of the contadorReducoes property.
     * 
     */
    public void setContadorReducoes(int value) {
        this.contadorReducoes = value;
    }

    /**
     * Gets the value of the numeroOperacaoInicial property.
     * 
     */
    public int getNumeroOperacaoInicial() {
        return numeroOperacaoInicial;
    }

    /**
     * Sets the value of the numeroOperacaoInicial property.
     * 
     */
    public void setNumeroOperacaoInicial(int value) {
        this.numeroOperacaoInicial = value;
    }

    /**
     * Gets the value of the numeroOperacaoFinal property.
     * 
     */
    public int getNumeroOperacaoFinal() {
        return numeroOperacaoFinal;
    }

    /**
     * Sets the value of the numeroOperacaoFinal property.
     * 
     */
    public void setNumeroOperacaoFinal(int value) {
        this.numeroOperacaoFinal = value;
    }

    /**
     * Gets the value of the movimentoTotalBrutoDia property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMovimentoTotalBrutoDia() {
        return movimentoTotalBrutoDia;
    }

    /**
     * Sets the value of the movimentoTotalBrutoDia property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMovimentoTotalBrutoDia(BigDecimal value) {
        this.movimentoTotalBrutoDia = value;
    }

    /**
     * Gets the value of the valorTotalCancelados property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValorTotalCancelados() {
        return valorTotalCancelados;
    }

    /**
     * Sets the value of the valorTotalCancelados property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValorTotalCancelados(BigDecimal value) {
        this.valorTotalCancelados = value;
    }

    /**
     * Gets the value of the valorTotalDescontos property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValorTotalDescontos() {
        return valorTotalDescontos;
    }

    /**
     * Sets the value of the valorTotalDescontos property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValorTotalDescontos(BigDecimal value) {
        this.valorTotalDescontos = value;
    }

    /**
     * Gets the value of the valorContabil property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValorContabil() {
        return valorContabil;
    }

    /**
     * Sets the value of the valorContabil property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValorContabil(BigDecimal value) {
        this.valorContabil = value;
    }

	/**
     * Gets the value of the gtInicial property.
     * 
     */
    public BigDecimal getGtInicial() {
		return gtInicial;
	}

    /**
     * Sets the value of the gtInicial property.
     * 
     */
	public void setGtInicial(BigDecimal gtInicial) {
		this.gtInicial = gtInicial;
	}

	/**
     * Gets the value of the gtFinal property.
     * 
     */
	public BigDecimal getGtFinal() {
		return gtFinal;
	}

    /**
     * Sets the value of the gtFinal property.
     * 
     */
	public void setGtFinal(BigDecimal gtFinal) {
		this.gtFinal = gtFinal;
	}

	/**
     * Gets the value of the quantidadeClientes property.
     * 
     */
    public long getQuantidadeClientes() {
        return quantidadeClientes;
    }

    /**
     * Sets the value of the quantidadeClientes property.
     * 
     */
    public void setQuantidadeClientes(long value) {
        this.quantidadeClientes = value;
    }

    /**
     * Gets the value of the acumuladorIsento property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAcumuladorIsento() {
        return acumuladorIsento;
    }

    /**
     * Sets the value of the acumuladorIsento property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAcumuladorIsento(BigDecimal value) {
        this.acumuladorIsento = value;
    }

    /**
     * Gets the value of the acumuladorNaoTributado property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAcumuladorNaoTributado() {
        return acumuladorNaoTributado;
    }

    /**
     * Sets the value of the acumuladorNaoTributado property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAcumuladorNaoTributado(BigDecimal value) {
        this.acumuladorNaoTributado = value;
    }

    /**
     * Gets the value of the acumuladorSubstituicaoTributaria property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAcumuladorSubstituicaoTributaria() {
        return acumuladorSubstituicaoTributaria;
    }

    /**
     * Sets the value of the acumuladorSubstituicaoTributaria property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAcumuladorSubstituicaoTributaria(BigDecimal value) {
        this.acumuladorSubstituicaoTributaria = value;
    }

    /**
     * Gets the value of the contadorReinicioOperacao property.
     * 
     */
    public int getContadorReinicioOperacao() {
        return contadorReinicioOperacao;
    }

    /**
     * Sets the value of the contadorReinicioOperacao property.
     * 
     */
    public void setContadorReinicioOperacao(int value) {
        this.contadorReinicioOperacao = value;
    }

    /**
     * Gets the value of the indicadorECFPeriferico property.
     * 
     */
	public String getIndicadorECFPeriferico() {
		return indicadorECFPeriferico;
	}

    /**
     * Sets the value of the indicadorECFPeriferico property.
     * 
     */
	public void setIndicadorECFPeriferico(String indicadorECFPeriferico) {
		this.indicadorECFPeriferico = indicadorECFPeriferico;
	}

}
