//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.01 at 10:44:21 PM BRT 
//


package com.dieboldnixdorf.frentecaixa.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;


/**
 * 
 *     			valor total de impostos PIS/Cofins por impressora fiscal
 *     			(PDV)
 *     		
 * 
 * <p>Java class for TotalPisCofinsPDVPayloadType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TotalPisCofinsPDVPayloadType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="numeroECF"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
 *               &lt;maxExclusive value="999"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="valorTotalPIS" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="valorTotalCOFINS" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TotalPisCofinsPDVPayloadType", propOrder = {
    "numeroECF",
    "valorTotalPIS",
    "valorTotalCOFINS"
})
@JsonPropertyOrder({ 
    "numeroECF",
    "valorTotalPIS",
    "valorTotalCOFINS"
})
public class TotalPisCofinsPDVPayloadType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    protected int numeroECF;
    @XmlElement(required = true)
    @JsonProperty("valorTotalPIS")
    @JsonSerialize(using = BigDecimalSerializer.class)
    protected BigDecimal valorTotalPIS;
    @XmlElement(required = true)
    @JsonProperty("valorTotalCOFINS")
    @JsonSerialize(using = BigDecimalSerializer.class)
    protected BigDecimal valorTotalCOFINS;

    /**
     * Gets the value of the numeroECF property.
     * 
     */
    public int getNumeroECF() {
        return numeroECF;
    }

    /**
     * Sets the value of the numeroECF property.
     * 
     */
    public void setNumeroECF(int value) {
        this.numeroECF = value;
    }

    /**
     * Gets the value of the valorTotalPIS property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValorTotalPIS() {
        return valorTotalPIS;
    }

    /**
     * Sets the value of the valorTotalPIS property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValorTotalPIS(BigDecimal value) {
        this.valorTotalPIS = value;
    }

    /**
     * Gets the value of the valorTotalCOFINS property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValorTotalCOFINS() {
        return valorTotalCOFINS;
    }

    /**
     * Sets the value of the valorTotalCOFINS property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValorTotalCOFINS(BigDecimal value) {
        this.valorTotalCOFINS = value;
    }

}
