//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.11 at 03:35:05 PM BRST 
//

package com.dieboldnixdorf.frentecaixa.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Calendar;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;


/**
 * <p>Java class for TEFPromocaoPayloadType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TEFPromocaoPayloadType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="dataMovimento" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="numeroPDV"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
 *               &lt;maxExclusive value="999"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="numeroTransacao"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}long"&gt;
 *               &lt;maxExclusive value="9999999999"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="recepcionistaDRT"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}long"&gt;
 *               &lt;maxExclusive value="999999999"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="numeroSetor"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
 *               &lt;maxExclusive value="999"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="nomeSetor"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="20"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="valorTotalTEFPromocaoSetor" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="tipoDesconto"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="OM"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TEFPromocaoPayloadType", propOrder = {
	"siglaLoja",
    "dataMovimento",
    "numeroPDV",
    "numeroTransacao",
    "recepcionistaDRT",
    "numeroSetor",
    "nomeSetor",
    "valorTotalTEFPromocaoSetor",
    "tipoDesconto"
})
@JsonPropertyOrder({ 
	"siglaLoja",
    "dataMovimento",
    "numeroPDV",
    "numeroTransacao",
    "recepcionistaDRT",
    "numeroSetor",
    "nomeSetor",
    "valorTotalTEFPromocaoSetor",
    "tipoDesconto"
})
public class TEFPromocaoPayloadType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    protected String siglaLoja;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    @JsonProperty("dataMovimento")
    @JsonSerialize(using = DataMovimentoSerializer.class)
    protected Calendar dataMovimento;
    protected int numeroPDV;
    protected long numeroTransacao;
    protected long recepcionistaDRT;
    protected int numeroSetor;
    @XmlElement(required = true)
    protected String nomeSetor;
    @XmlElement(required = true)
    @JsonProperty("valorTotalTEFPromocaoSetor")
    @JsonSerialize(using = BigDecimalSerializer.class)
    protected BigDecimal valorTotalTEFPromocaoSetor;
    @XmlElement(required = true)
    protected String tipoDesconto;

    /**
     * Gets the value of the siglaLoja property.
     *
     * @return the sigla loja
     */
    public String getSiglaLoja() {
		return siglaLoja;
	}

    /**
     * Sets the value of the siglaLoja property.
     * 
     */
	public void setSiglaLoja(String siglaLoja) {
		this.siglaLoja = siglaLoja;
	}

    /**
     * Gets the value of the dataMovimento property.
     * 
     * @return
     *     possible object is
     *     {@link Calendar }
     *     
     */
    public Calendar getDataMovimento() {
        return dataMovimento;
    }

    /**
     * Sets the value of the dataMovimento property.
     * 
     * @param value
     *     allowed object is
     *     {@link Calendar }
     *     
     */
    public void setDataMovimento(Calendar value) {
        this.dataMovimento = value;
    }

    /**
     * Gets the value of the numeroPDV property.
     * 
     */
    public int getNumeroPDV() {
        return numeroPDV;
    }

    /**
     * Sets the value of the numeroPDV property.
     * 
     */
    public void setNumeroPDV(int value) {
        this.numeroPDV = value;
    }

    /**
     * Gets the value of the numeroTransacao property.
     * 
     */
    public long getNumeroTransacao() {
        return numeroTransacao;
    }

    /**
     * Sets the value of the numeroTransacao property.
     * 
     */
    public void setNumeroTransacao(long value) {
        this.numeroTransacao = value;
    }

    /**
     * Gets the value of the recepcionistaDRT property.
     * 
     */
    public long getRecepcionistaDRT() {
        return recepcionistaDRT;
    }

    /**
     * Sets the value of the recepcionistaDRT property.
     * 
     */
    public void setRecepcionistaDRT(long value) {
        this.recepcionistaDRT = value;
    }

    /**
     * Gets the value of the numeroSetor property.
     * 
     */
    public int getNumeroSetor() {
        return numeroSetor;
    }

    /**
     * Sets the value of the numeroSetor property.
     * 
     */
    public void setNumeroSetor(int value) {
        this.numeroSetor = value;
    }

    /**
     * Gets the value of the nomeSetor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNomeSetor() {
        return nomeSetor;
    }

    /**
     * Sets the value of the nomeSetor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNomeSetor(String value) {
        this.nomeSetor = value;
    }

    /**
     * Gets the value of the valorTotalTEFPromocaoSetor property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValorTotalTEFPromocaoSetor() {
        return valorTotalTEFPromocaoSetor;
    }

    /**
     * Sets the value of the valorTotalTEFPromocaoSetor property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValorTotalTEFPromocaoSetor(BigDecimal value) {
        this.valorTotalTEFPromocaoSetor = value;
    }

    /**
     * Gets the value of the tipoDesconto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoDesconto() {
        return tipoDesconto;
    }

    /**
     * Sets the value of the tipoDesconto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoDesconto(String value) {
        this.tipoDesconto = value;
    }

}
