//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.11 at 03:35:05 PM BRST 
//


package com.dieboldnixdorf.frentecaixa.domain;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.dieboldnixdorf.frentecaixa.domain.SocioTorcedorPayloadType;
import com.dieboldnixdorf.frentecaixa.domain.CabecalhoType;


/**
 * <p>Java class for SocioTorcedorMessageType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SocioTorcedorMessageType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="cabecalho" type="{http://www.dieboldnixdorf.com/frentecaixa/TipoCabecalho}CabecalhoType"/&gt;
 *         &lt;element name="transacaoSocioTorcedor" type="{http://www.dieboldnixdorf.com/frentecaixa/SocioTorcedorPayload}SocioTorcedorPayloadType" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SocioTorcedorMessageType", propOrder = {
    "cabecalho",
    "transacaoSocioTorcedor"
})
public class SocioTorcedorMessageType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected CabecalhoType cabecalho;
    @XmlElement(required = true)
    protected List<SocioTorcedorPayloadType> transacaoSocioTorcedor;

    /**
     * Gets the value of the cabecalho property.
     * 
     * @return
     *     possible object is
     *     {@link CabecalhoType }
     *     
     */
    public CabecalhoType getCabecalho() {
        return cabecalho;
    }

    /**
     * Sets the value of the cabecalho property.
     * 
     * @param value
     *     allowed object is
     *     {@link CabecalhoType }
     *     
     */
    public void setCabecalho(CabecalhoType value) {
        this.cabecalho = value;
    }

    /**
     * Gets the value of the transacaoSocioTorcedor property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the transacaoSocioTorcedor property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTransacaoSocioTorcedor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SocioTorcedorPayloadType }
     * 
     * 
     */
    public List<SocioTorcedorPayloadType> getTransacaoSocioTorcedor() {
        if (transacaoSocioTorcedor == null) {
            transacaoSocioTorcedor = new ArrayList<SocioTorcedorPayloadType>();
        }
        return this.transacaoSocioTorcedor;
    }

}
