//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.11 at 03:35:05 PM BRST 
//


package com.dieboldnixdorf.frentecaixa.domain;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import com.dieboldnixdorf.frentecaixa.domain.TipoProdutosDescontosType;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;


/**
 * <p>Java class for SocioTorcedorPayloadType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SocioTorcedorPayloadType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="numeroTransacao"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}long"&gt;
 *               &lt;maxExclusive value="999999999"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="DRTOperador"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}long"&gt;
 *               &lt;maxExclusive value="999999999"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="CPFSocioTorcedor"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="11"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="dataMovimentacao" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="produtosAmbevDescontos" type="{http://www.dieboldnixdorf.com/frentecaixa/TipoProdutosDescontos}TipoProdutosDescontosType" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SocioTorcedorPayloadType", propOrder = {
    "siglaLoja",
    "numeroPDV",
    "numeroTransacao",
    "drtOperador",
    "cpfSocioTorcedor",
    "dataMovimentacao",
    "produtosAmbevDescontos"
})
@JsonPropertyOrder({ 
    "siglaLoja",
    "numeroPDV",
    "numeroTransacao",
    "drtOperador",
    "cpfSocioTorcedor",
    "dataMovimentacao",
    "produtosAmbevDescontos"
})
public class SocioTorcedorPayloadType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    protected long numeroTransacao;
    @XmlElement(name = "drtOperador")
    protected long drtOperador;
    @XmlElement(name = "cpfSocioTorcedor", required = true)
    protected String cpfSocioTorcedor;
    @XmlElement(required = true, type = String.class)
    @XmlSchemaType(name = "dateTime")
    @JsonProperty("dataMovimentacao")
    @JsonSerialize(using = DataMovimentacaoSerializer.class)
    protected Calendar dataMovimentacao;
    protected Integer numeroPDV;
    protected String siglaLoja;
    @XmlElement(required = true)
    protected List<TipoProdutosDescontosType> produtosAmbevDescontos;

    /**
     * Gets the value of the numeroTransacao property.
     * 
     */
    public long getNumeroTransacao() {
        return numeroTransacao;
    }

    /**
     * Sets the value of the numeroTransacao property.
     * 
     */
    public void setNumeroTransacao(long value) {
        this.numeroTransacao = value;
    }

    /**
     * Gets the value of the drtOperador property.
     * 
     */
    public long getDrtOperador() {
        return drtOperador;
    }

    /**
     * Sets the value of the drtOperador property.
     * 
     */
    public void setDrtOperador(long value) {
        this.drtOperador = value;
    }

    /**
     * Gets the value of the cpfSocioTorcedor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCpfSocioTorcedor() {
        return cpfSocioTorcedor;
    }

    /**
     * Sets the value of the cpfSocioTorcedor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCpfSocioTorcedor(String value) {
        this.cpfSocioTorcedor = value;
    }

    /**
     * Gets the value of the dataMovimentacao property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Calendar getDataMovimentacao() {
        return dataMovimentacao;
    }

    /**
     * Sets the value of the dataMovimentacao property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataMovimentacao(Calendar value) {
        this.dataMovimentacao = value;
    }

    /**
     * Gets the value of the numeroPDV property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNumeroPDV() {
		return numeroPDV;
	}

    /**
     * Sets the value of the numeroPDV property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
	public void setNumeroPDV(Integer numeroPDV) {
		this.numeroPDV = numeroPDV;
	}

    /**
     * Gets the value of the siglaLoja property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
	public String getSiglaLoja() {
		return siglaLoja;
	}

    /**
     * Sets the value of the siglaLoja property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
	public void setSiglaLoja(String siglaLoja) {
		this.siglaLoja = siglaLoja;
	}

	/**
     * Gets the value of the produtosAmbevDescontos property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the produtosAmbevDescontos property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProdutosAmbevDescontos().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TipoProdutosDescontosType }
     * 
     * 
     */
    public List<TipoProdutosDescontosType> getProdutosAmbevDescontos() {
        if (produtosAmbevDescontos == null) {
            produtosAmbevDescontos = new ArrayList<TipoProdutosDescontosType>();
        }
        return this.produtosAmbevDescontos;
    }

}
