//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.11 at 03:35:05 PM BRST 
//


package com.dieboldnixdorf.frentecaixa.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;


/**
 * <p>Java class for TipoProdutoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TipoProdutoType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="EAN" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="quantidade" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="valorDesconto" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TipoProdutoType", propOrder = {
    "ean",
    "quantidade",
    "valorDesconto"
})
@JsonPropertyOrder({ 
    "ean",
    "quantidade",
    "valorDesconto"
})
public class TipoProdutoType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "EAN")
    protected long ean;
    @XmlElement(required = true)
    @JsonProperty("quantidade")
    @JsonSerialize(using = QuantidadeProdutoDescontoSerializer.class)
    protected BigDecimal quantidade;
    @XmlElement(required = true)
    @JsonProperty("valorDesconto")
    @JsonSerialize(using = BigDecimalSerializer.class)
    protected BigDecimal valorDesconto;

    /**
     * Gets the value of the ean property.
     * 
     */
    public long getEAN() {
        return ean;
    }

    /**
     * Sets the value of the ean property.
     * 
     */
    public void setEAN(long value) {
        this.ean = value;
    }

    /**
     * Gets the value of the quantidade property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getQuantidade() {
        return quantidade;
    }

    /**
     * Sets the value of the quantidade property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setQuantidade(BigDecimal value) {
        this.quantidade = value;
    }

    /**
     * Gets the value of the valorDesconto property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValorDesconto() {
        return valorDesconto;
    }

    /**
     * Sets the value of the valorDesconto property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValorDesconto(BigDecimal value) {
        this.valorDesconto = value;
    }

}
