//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.11 at 03:35:05 PM BRST 
//


package com.dieboldnixdorf.frentecaixa.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Calendar;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;


/**
 * formato HHMM
 * 
 * <p>Java class for OperacoesPDVBalcaoPayloadType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OperacoesPDVBalcaoPayloadType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;choice&gt;
 *           &lt;element name="numeroPDV" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *           &lt;element name="numeroBalcao" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;/choice&gt;
 *         &lt;element name="dataMovimentacao" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="dataAtual" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="DRTFiscalizador" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;choice&gt;
 *           &lt;element name="numeroTransacao" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *           &lt;element name="numeroCupom" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;/choice&gt;
 *         &lt;element name="departamento" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="produto" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="descricaoProduto" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="quantidadeProduto" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="valor" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="tipoRetorno"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="CP"/&gt;
 *               &lt;enumeration value="DV"/&gt;
 *               &lt;enumeration value="CANC"/&gt;
 *               &lt;enumeration value="TC"/&gt;
 *               &lt;enumeration value="NA"/&gt;
 *               &lt;enumeration value="BG"/&gt;
 *               &lt;enumeration value="RD"/&gt;
 *               &lt;enumeration value="CPC"/&gt;
 *               &lt;enumeration value="DIV"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="descritivoRetorno" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="drt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OperacoesPDVBalcaoPayloadType", propOrder = {
	"siglaLoja",
    "numeroPDVBalcao",
    "dataMovimentacao",
    "dataAtual",
    "drtFiscalizador",
    "numeroTransacao",
    "departamento",
    "produto",
    "descricaoProduto",
    "quantidadeProduto",
    "valor",
    "tipoRetorno",
    "descritivoRetorno",
    "drt"
})
@JsonPropertyOrder({ 
	"siglaLoja",
    "numeroPDVBalcao",
    "dataMovimentacao",
    "dataAtual",
    "drtFiscalizador",
    "numeroTransacao",
    "departamento",
    "produto",
    "descricaoProduto",
    "quantidadeProduto",
    "valor",
    "tipoRetorno",
    "descritivoRetorno",
    "drt"
  
})
public class OperacoesPDVBalcaoPayloadType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    protected String siglaLoja;
    protected String numeroPDVBalcao;
    @XmlElement(required = true, type = String.class)
    @XmlSchemaType(name = "dateTime")
    @JsonProperty("dataMovimentacao")
    @JsonSerialize(using = DataMovimentacaoSerializer.class)
    protected Calendar dataMovimentacao;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    @JsonProperty("dataAtual")
    @JsonSerialize(using = DataAtualSerializer.class)
    protected Calendar dataAtual;
    @XmlElement(name = "drtFiscalizador")
    protected Long drtFiscalizador;
    protected String numeroTransacao;
    protected int departamento;
    @XmlElement(required = true)
    protected Long produto;
    @XmlElement(required = true)
    protected String descricaoProduto;
    @XmlElement(required = true)
    @JsonProperty("quantidadeProduto")
    @JsonSerialize(using = BigDecimal3Serializer.class)
    protected BigDecimal quantidadeProduto;
    @XmlElement(required = true)
    @JsonProperty("valor")
    @JsonSerialize(using = BigDecimalSerializer.class)
    protected BigDecimal valor;
    @XmlElement(required = true)
    protected String tipoRetorno;
    @XmlElement(required = true)
    protected String descritivoRetorno;
    protected String drt;
    protected String matricula;

    /**
     * Gets the value of the siglaLoja property.
     *
     * @return the sigla loja
     */
    public String getSiglaLoja() {
		return siglaLoja;
	}

    /**
     * Sets the value of the siglaLoja property.
     * 
     */
	public void setSiglaLoja(String siglaLoja) {
		this.siglaLoja = siglaLoja;
	}


    /**
     * Gets the value of the numeroBalcao property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroPDVBalcao() {
        return numeroPDVBalcao;
    }

    /**
     * Sets the value of the numeroBalcao property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumeroPDVBalcao(String value) {
        this.numeroPDVBalcao = value;
    }

    /**
     * Gets the value of the dataMovimentacao property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Calendar getDataMovimentacao() {
        return dataMovimentacao;
    }

    /**
     * Sets the value of the dataMovimentacao property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataMovimentacao(Calendar value) {
        this.dataMovimentacao = value;
    }

    /**
     * Gets the value of the dataAtual property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public Calendar getDataAtual() {
        return dataAtual;
    }

    /**
     * Sets the value of the dataAtual property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDataAtual(Calendar value) {
        this.dataAtual = value;
    }

    /**
     * Gets the value of the drtFiscalizador property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getDrtFiscalizador() {
        return drtFiscalizador;
    }

    /**
     * Sets the value of the drtFiscalizador property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setDrtFiscalizador(Long value) {
        this.drtFiscalizador = value;
    }


    /**
     * Gets the value of the numeroCupom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroTransacao() {
        return numeroTransacao;
    }

    /**
     * Sets the value of the numeroCupom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumeroTransacao(String value) {
        this.numeroTransacao = value;
    }

    /**
     * Gets the value of the departamento property.
     * 
     */
    public int getDepartamento() {
        return departamento;
    }

    /**
     * Sets the value of the departamento property.
     * 
     */
    public void setDepartamento(int value) {
        this.departamento = value;
    }

    /**
     * Gets the value of the produto property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getProduto() {
        return produto;
    }

    /**
     * Sets the value of the produto property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setProduto(Long value) {
        this.produto = value;
    }

    /**
     * Gets the value of the descricaoProduto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescricaoProduto() {
        return descricaoProduto;
    }

    /**
     * Sets the value of the descricaoProduto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescricaoProduto(String value) {
        this.descricaoProduto = value;
    }

    /**
     * Gets the value of the quantidadeProduto property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getQuantidadeProduto() {
        return quantidadeProduto;
    }

    /**
     * Sets the value of the quantidadeProduto property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setQuantidadeProduto(BigDecimal value) {
        this.quantidadeProduto = value;
    }

    /**
     * Gets the value of the valor property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValor() {
        return valor;
    }

    /**
     * Sets the value of the valor property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValor(BigDecimal value) {
        this.valor = value;
    }

    /**
     * Gets the value of the tipoRetorno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoRetorno() {
        return tipoRetorno;
    }

    /**
     * Sets the value of the tipoRetorno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoRetorno(String value) {
        this.tipoRetorno = value;
    }

    /**
     * Gets the value of the descritivoRetorno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescritivoRetorno() {
        return descritivoRetorno;
    }

    /**
     * Sets the value of the descritivoRetorno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescritivoRetorno(String value) {
        this.descritivoRetorno = value;
    }

    /**
     * Gets the value of the drt property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public String getDrt() {
        return drt;
    }

    /**
     * Sets the value of the drt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setDrt(String value) {
        this.drt = value;
    }
   

}
