//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.08 at 02:15:33 PM BRT 
//


package com.dieboldnixdorf.frentecaixa.domain;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * <p>Java class for OperadoraLojaPayloadType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OperadoraLojaPayloadType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="NumDRT" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="NomeOperador" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="PerfilOperador" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OperadoraLojaPayloadType", propOrder = {
	"siglaLoja",
    "numDRT",
    "nomeOperador",
    "perfilOperador"
})
@JsonPropertyOrder({ 
	"siglaLoja",
    "numDRT",
    "nomeOperador",
    "perfilOperador"
})
public class OperadoraLojaPayloadType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "siglaLoja", required = true)
    protected String siglaLoja;
    @XmlElement(name = "numDRT")
    protected long numDRT;
    @XmlElement(name = "nomeOperador", required = true)
    protected String nomeOperador;
    @XmlElement(name = "perfilOperador")
    protected int perfilOperador;

    /**
     * Gets the value of the siglaLoja property.
     *
     * @return the sigla loja
     */
    public String getSiglaLoja() {
		return siglaLoja;
	}

    /**
     * Sets the value of the siglaLoja property.
     * 
     */
	public void setSiglaLoja(String siglaLoja) {
		this.siglaLoja = siglaLoja;
	}

	/**
     * Gets the value of the numDRT property.
     * 
     */
    public long getNumDRT() {
        return numDRT;
    }

    /**
     * Sets the value of the numDRT property.
     * 
     */
    public void setNumDRT(long value) {
        this.numDRT = value;
    }

    /**
     * Gets the value of the nomeOperador property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNomeOperador() {
        return nomeOperador;
    }

    /**
     * Sets the value of the nomeOperador property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNomeOperador(String value) {
        this.nomeOperador = value;
    }

    /**
     * Gets the value of the perfilOperador property.
     * 
     */
    public int getPerfilOperador() {
        return perfilOperador;
    }

    /**
     * Sets the value of the perfilOperador property.
     * 
     */
    public void setPerfilOperador(int value) {
        this.perfilOperador = value;
    }

}
