//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.11 at 03:35:05 PM BRST 
//


package com.dieboldnixdorf.frentecaixa.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Calendar;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;


/**
 * <p>Java class for VendaSetorDiariaPayloadType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VendaSetorDiariaPayloadType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="codigoSecao"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
 *               &lt;maxExclusive value="99"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="valorContabil" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="valorICMS" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="valorBaseCalculoPIS" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="valorBaseCalculoCOFINS" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="valorPIS" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="valorCOFINS" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VendaSetorDiariaPayloadType", propOrder = {
    "codigoSecao",
    "dataMovimentoVendasSetor",
    "valorContabil",
    "valorICMS",
    "valorBaseCalculoPIS",
    "valorBaseCalculoCOFINS",
    "valorPIS",
    "valorCOFINS"
})
@JsonPropertyOrder({ 
    "codigoSecao",
    "dataMovimentoVendasSetor",
    "valorContabil",
    "valorICMS",
    "valorBaseCalculoPIS",
    "valorBaseCalculoCOFINS",
    "valorPIS",
    "valorCOFINS"
})
public class VendaSetorDiariaPayloadType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    protected int codigoSecao;
    @JsonProperty("dataMovimentoVendasSetor")
    @JsonSerialize(using = DataMovimentacaoSerializer.class)
    protected Calendar dataMovimentoVendasSetor;
    @XmlElement(required = true)
    @JsonProperty("valorContabil")
    @JsonSerialize(using = BigDecimalSerializer.class)
    protected BigDecimal valorContabil;
    @XmlElement(required = true)
    @JsonProperty("valorICMS")
    @JsonSerialize(using = BigDecimalSerializer.class)
    protected BigDecimal valorICMS;
    @XmlElement(required = true)
    @JsonProperty("valorBaseCalculoPIS")
    @JsonSerialize(using = BigDecimalSerializer.class)
    protected BigDecimal valorBaseCalculoPIS;
    @XmlElement(required = true)
    @JsonProperty("valorBaseCalculoCOFINS")
    @JsonSerialize(using = BigDecimalSerializer.class)
    protected BigDecimal valorBaseCalculoCOFINS;
    @XmlElement(required = true)
    @JsonProperty("valorPIS")
    @JsonSerialize(using = BigDecimalSerializer.class)
    protected BigDecimal valorPIS;
    @XmlElement(required = true)
    @JsonProperty("valorCOFINS")
    @JsonSerialize(using = BigDecimalSerializer.class)
    protected BigDecimal valorCOFINS;

    /**
     * Gets the value of the codigoSecao property.
     * 
     */
    public int getCodigoSecao() {
        return codigoSecao;
    }

    /**
     * Sets the value of the codigoSecao property.
     * 
     */
    public void setCodigoSecao(int value) {
        this.codigoSecao = value;
    }

	/**
     * Gets the value of the dataMovimentoVendasSetor property.
     * 
     * @return
     *     possible object is
     *     {@link Calendar }
     *     
     */
    public Calendar getDataMovimentoVendasSetor() {
		return dataMovimentoVendasSetor;
	}

    /**
     * Sets the value of the dataMovimentoVendasSetor property.
     * 
     */
	public void setDataMovimentoVendasSetor(Calendar dataMovimentoVendasSetor) {
		this.dataMovimentoVendasSetor = dataMovimentoVendasSetor;
	}

	/**
     * Gets the value of the valorContabil property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValorContabil() {
        return valorContabil;
    }

    /**
     * Sets the value of the valorContabil property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValorContabil(BigDecimal value) {
        this.valorContabil = value;
    }

    /**
     * Gets the value of the valorICMS property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValorICMS() {
        return valorICMS;
    }

    /**
     * Sets the value of the valorICMS property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValorICMS(BigDecimal value) {
        this.valorICMS = value;
    }

    /**
     * Gets the value of the valorBaseCalculoPIS property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValorBaseCalculoPIS() {
        return valorBaseCalculoPIS;
    }

    /**
     * Sets the value of the valorBaseCalculoPIS property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValorBaseCalculoPIS(BigDecimal value) {
        this.valorBaseCalculoPIS = value;
    }

    /**
     * Gets the value of the valorBaseCalculoCOFINS property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValorBaseCalculoCOFINS() {
        return valorBaseCalculoCOFINS;
    }

    /**
     * Sets the value of the valorBaseCalculoCOFINS property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValorBaseCalculoCOFINS(BigDecimal value) {
        this.valorBaseCalculoCOFINS = value;
    }

    /**
     * Gets the value of the valorPIS property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValorPIS() {
        return valorPIS;
    }

    /**
     * Sets the value of the valorPIS property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValorPIS(BigDecimal value) {
        this.valorPIS = value;
    }

    /**
     * Gets the value of the valorCOFINS property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValorCOFINS() {
        return valorCOFINS;
    }

    /**
     * Sets the value of the valorCOFINS property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValorCOFINS(BigDecimal value) {
        this.valorCOFINS = value;
    }

}
