//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.11 at 03:35:05 PM BRST 
//


package com.dieboldnixdorf.frentecaixa.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;


/**
 * <p>Java class for TrocaDevolucaoPayloadType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TrocaDevolucaoPayloadType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="codigoProdutoEAN"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}long"&gt;
 *               &lt;maxExclusive value="9999999999999"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="valorProduto" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="codigoOperacao"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="TC "/&gt;
 *               &lt;enumeration value="RD"/&gt;
 *               &lt;enumeration value="CP"/&gt;
 *               &lt;enumeration value="AN"/&gt;
 *               &lt;enumeration value="DO"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="quantidadeProduto" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="razaoOperacao"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
 *               &lt;maxExclusive value="99"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="trocaComCuponFiscal"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="S"/&gt;
 *               &lt;enumeration value="N"/&gt;
 *               &lt;length value="1"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="numeroCuponFiscal" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="9"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="figuraFiscal" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="2"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TrocaDevolucaoPayloadType", propOrder = {
	"siglaLoja",
    "codigoProdutoEAN",
    "valorProduto",
    "codigoOperacao",
    "quantidadeProduto",
    "razaoOperacao",
    "trocaComCupomFiscal",
    "numeroCupomFiscal",
    "figuraFiscal"
})
@JsonPropertyOrder({ 
	"siglaLoja",
    "codigoProdutoEAN",
    "valorProduto",
    "codigoOperacao",
    "quantidadeProduto",
    "razaoOperacao",
    "trocaComCupomFiscal",
    "numeroCupomFiscal",
    "figuraFiscal"
})
public class TrocaDevolucaoPayloadType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    protected String siglaLoja;
    protected long codigoProdutoEAN;
    @XmlElement(required = true)
    @JsonProperty("valorProduto")
    @JsonSerialize(using = BigDecimal9Serializer.class)
    protected BigDecimal valorProduto;
    @XmlElement(required = true)
    protected String codigoOperacao;
    @XmlElement(required = true)
    @JsonProperty("quantidadeProduto")
    @JsonSerialize(using = BigDecimal9Serializer.class)
    protected BigDecimal quantidadeProduto;
    protected int razaoOperacao;
    @XmlElement(required = true)
    protected String trocaComCupomFiscal;
    protected Long numeroCupomFiscal;
    protected String figuraFiscal;

    /**
     * Gets the value of the siglaLoja property.
     *
     * @return the sigla loja
     */
    public String getSiglaLoja() {
		return siglaLoja;
	}

    /**
     * Sets the value of the siglaLoja property.
     * 
     */
	public void setSiglaLoja(String siglaLoja) {
		this.siglaLoja = siglaLoja;
	}

    /**
     * Gets the value of the codigoProdutoEAN property.
     * 
     */
    public long getCodigoProdutoEAN() {
        return codigoProdutoEAN;
    }

    /**
     * Sets the value of the codigoProdutoEAN property.
     * 
     */
    public void setCodigoProdutoEAN(long value) {
        this.codigoProdutoEAN = value;
    }

    /**
     * Gets the value of the valorProduto property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValorProduto() {
        return valorProduto;
    }

    /**
     * Sets the value of the valorProduto property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValorProduto(BigDecimal value) {
        this.valorProduto = value;
    }

    /**
     * Gets the value of the codigoOperacao property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoOperacao() {
        return codigoOperacao;
    }

    /**
     * Sets the value of the codigoOperacao property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoOperacao(String value) {
        this.codigoOperacao = value;
    }

    /**
     * Gets the value of the quantidadeProduto property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getQuantidadeProduto() {
        return quantidadeProduto;
    }

    /**
     * Sets the value of the quantidadeProduto property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setQuantidadeProduto(BigDecimal value) {
        this.quantidadeProduto = value;
    }

    /**
     * Gets the value of the razaoOperacao property.
     * 
     */
    public int getRazaoOperacao() {
        return razaoOperacao;
    }

    /**
     * Sets the value of the razaoOperacao property.
     * 
     */
    public void setRazaoOperacao(int value) {
        this.razaoOperacao = value;
    }

    /**
     * Gets the value of the trocaComCupomFiscal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrocaComCupomFiscal() {
        return trocaComCupomFiscal;
    }

    /**
     * Sets the value of the trocaComCupomFiscal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrocaComCupomFiscal(String value) {
        this.trocaComCupomFiscal = value;
    }

    /**
     * Gets the value of the numeroCupomFiscal property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getNumeroCupomFiscal() {
        return numeroCupomFiscal;
    }

    /**
     * Sets the value of the numeroCupomFiscal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setNumeroCupomFiscal(Long value) {
        this.numeroCupomFiscal = value;
    }

    /**
     * Gets the value of the figuraFiscal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFiguraFiscal() {
        return figuraFiscal;
    }

    /**
     * Sets the value of the figuraFiscal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFiguraFiscal(String value) {
        this.figuraFiscal = value;
    }

}
