//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.14 at 10:40:05 PM BRT 
//


package com.dieboldnixdorf.frentecaixa.domain;

import java.io.Serializable;
import java.util.Calendar;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;


/**
 * Data do Movimento
 * 
 * <p>Java class for ClienteLojaPayloadType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ClienteLojaPayloadType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="loja" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="siglaLoja"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="3"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="dataMovimento" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="setores" type="{http://www.dieboldnixdorf.com/frentecaixa/TipoSetoresLoja}TipoSetoresLojaType"/&gt;
 *         &lt;element name="totalizacaoLoja" type="{http://www.dieboldnixdorf.com/frentecaixa/TipoLojaFim}TipoLojaFimType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ClienteLojaPayloadType", propOrder = {
    "loja",
    "siglaLoja",
    "dataMovimento",
    "setores",
    "totalizacaoLoja"
})
@JsonPropertyOrder({ 
    "loja",
    "siglaLoja",
    "dataMovimento",
    "setores",
    "totalizacaoLoja"
})
public class ClienteLojaPayloadType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected String loja;
    @XmlElement(required = true)
    protected String siglaLoja;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    @JsonProperty("dataMovimento")
    @JsonSerialize(using = DataMovimentoSerializer.class)
    protected Calendar dataMovimento;
    @XmlElement(required = true)
    protected TipoSetoresLojaType setores;
    @XmlElement(required = true)
    protected TipoLojaFimType totalizacaoLoja;

    /**
     * Gets the value of the loja property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoja() {
        return loja;
    }

    /**
     * Sets the value of the loja property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoja(String value) {
        this.loja = value;
    }

    /**
     * Gets the value of the siglaLoja property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSiglaLoja() {
        return siglaLoja;
    }

    /**
     * Sets the value of the siglaLoja property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSiglaLoja(String value) {
        this.siglaLoja = value;
    }

    /**
     * Gets the value of the dataMovimento property.
     * 
     * @return
     *     possible object is
     *     {@link Calendar }
     *     
     */
    public Calendar getDataMovimento() {
        return dataMovimento;
    }

    /**
     * Sets the value of the dataMovimento property.
     * 
     * @param value
     *     allowed object is
     *     {@link Calendar }
     *     
     */
    public void setDataMovimento(Calendar value) {
        this.dataMovimento = value;
    }

    /**
     * Gets the value of the setores property.
     * 
     * @return
     *     possible object is
     *     {@link TipoSetoresLojaType }
     *     
     */
    public TipoSetoresLojaType getSetores() {
        return setores;
    }

    /**
     * Sets the value of the setores property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoSetoresLojaType }
     *     
     */
    public void setSetores(TipoSetoresLojaType value) {
        this.setores = value;
    }

    /**
     * Gets the value of the totalizacaoLoja property.
     * 
     * @return
     *     possible object is
     *     {@link TipoLojaFimType }
     *     
     */
    public TipoLojaFimType getTotalizacaoLoja() {
        return totalizacaoLoja;
    }

    /**
     * Sets the value of the totalizacaoLoja property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoLojaFimType }
     *     
     */
    public void setTotalizacaoLoja(TipoLojaFimType value) {
        this.totalizacaoLoja = value;
    }

}
