//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.14 at 10:40:05 PM BRT 
//


package com.dieboldnixdorf.frentecaixa.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.dieboldnixdorf.frentecaixa.domain.TipoDepartamentosType;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;


/**
 * <p>Java class for TipoSetorType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TipoSetorType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="setor" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="codigoSetor" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="valorVendaLiquida" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="quantidadeUnidadesSetor" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="quantidadeClientesSetor" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="quantidadeClientesPerifericosSetor" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="departamentos" type="{http://www.dieboldnixdorf.com/frentecaixa/TipoDepartamentos}TipoDepartamentosType" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TipoSetorType", propOrder = {
    "setor",
    "codigoSetor",
    "valorVendaLiquida",
    "quantidadeUnidadesSetor",
    "quantidadeClientesSetor",
    "quantidadeClientesPerifericosSetor",
    "departamentos"
})
@JsonPropertyOrder({ 
    "setor",
    "codigoSetor",
    "valorVendaLiquida",
    "quantidadeUnidadesSetor",
    "quantidadeClientesSetor",
    "quantidadeClientesPerifericosSetor",
    "departamentos"
})
public class TipoSetorType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected String setor;
    protected int codigoSetor;
    @XmlElement(required = true)
    @JsonProperty("valorVendaLiquida")
    @JsonSerialize(using = BigDecimal7Serializer.class)
    protected BigDecimal valorVendaLiquida;
    @XmlElement(required = true)
    @JsonProperty("quantidadeUnidadesSetor")
    @JsonSerialize(using = BigDecimal17Serializer.class)
    protected BigDecimal quantidadeUnidadesSetor;
    @XmlElement(required = true)
    protected Long quantidadeClientesSetor;
    @XmlElement(required = true)
    protected Long quantidadeClientesPerifericosSetor;
    @XmlElement(required = true)
    protected List<TipoDepartamentosType> departamentos;

    /**
     * Gets the value of the setor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSetor() {
        return setor;
    }

    /**
     * Sets the value of the setor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSetor(String value) {
        this.setor = value;
    }

    /**
     * Gets the value of the codigoSetor property.
     * 
     */
    public int getCodigoSetor() {
        return codigoSetor;
    }

    /**
     * Sets the value of the codigoSetor property.
     * 
     */
    public void setCodigoSetor(int value) {
        this.codigoSetor = value;
    }

    /**
     * Gets the value of the valorVendaLiquida property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValorVendaLiquida() {
        return valorVendaLiquida;
    }

    /**
     * Sets the value of the valorVendaLiquida property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValorVendaLiquida(BigDecimal value) {
        this.valorVendaLiquida = value;
    }

    /**
     * Gets the value of the quantidadeUnidadesSetor property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getQuantidadeUnidadesSetor() {
        return quantidadeUnidadesSetor;
    }

    /**
     * Sets the value of the quantidadeUnidadesSetor property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setQuantidadeUnidadesSetor(BigDecimal value) {
        this.quantidadeUnidadesSetor = value;
    }

    /**
     * Gets the value of the quantidadeClientesSetor property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getQuantidadeClientesSetor() {
        return quantidadeClientesSetor;
    }

    /**
     * Sets the value of the quantidadeClientesSetor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setQuantidadeClientesSetor(Long value) {
        this.quantidadeClientesSetor = value;
    }

    /**
     * Gets the value of the quantidadeClientesPerifericosSetor property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getQuantidadeClientesPerifericosSetor() {
        return quantidadeClientesPerifericosSetor;
    }

    /**
     * Sets the value of the quantidadeClientesPerifericosSetor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setQuantidadeClientesPerifericosSetor(Long value) {
        this.quantidadeClientesPerifericosSetor = value;
    }

    /**
     * Gets the value of the departamentos property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the departamentos property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDepartamentos().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TipoDepartamentosType }
     * 
     * 
     */
    public List<TipoDepartamentosType> getDepartamentos() {
        if (departamentos == null) {
            departamentos = new ArrayList<TipoDepartamentosType>();
        }
        return this.departamentos;
    }

}
