//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.11 at 03:35:05 PM BRST 
//


package com.dieboldnixdorf.frentecaixa.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;


/**
 * <p>Java class for TransacoesECFAliquotaPayloadType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TransacoesECFAliquotaPayloadType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="numeroECF"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
 *               &lt;maxExclusive value="999"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="baseCalculo" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="tipoAliquota"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="IS"/&gt;
 *               &lt;enumeration value="NT"/&gt;
 *               &lt;enumeration value="ST"/&gt;
 *               &lt;enumeration value="BR"/&gt;
 *               &lt;enumeration value="CB"/&gt;
 *               &lt;enumeration value="PI"/&gt;
 *               &lt;enumeration value="DZ"/&gt;
 *               &lt;enumeration value="NO"/&gt;
 *               &lt;enumeration value="SU"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="valorAliquota" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="impostoDebitado" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TransacoesECFAliquotaPayloadType", propOrder = {
    "numeroECF",
    "baseCalculo",
    "tipoAliquota",
    "valorAliquota",
    "impostoDebitado"
})
@JsonPropertyOrder({ 
    "numeroECF",
    "baseCalculo",
    "tipoAliquota",
    "valorAliquota",
    "impostoDebitado"
})
public class TransacoesECFAliquotaPayloadType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    protected int numeroECF;
    @XmlElement(required = true)
    @JsonProperty("baseCalculo")
    @JsonSerialize(using = BigDecimalSerializer.class)
    protected BigDecimal baseCalculo;
    @XmlElement(required = true)
    protected String tipoAliquota;
    @XmlElement(required = true)
    @JsonProperty("valorAliquota")
    @JsonSerialize(using = BigDecimal4Serializer.class)
    protected BigDecimal valorAliquota;
    @XmlElement(required = true)
    @JsonProperty("impostoDebitado")
    @JsonSerialize(using = BigDecimalSerializer.class)
    protected BigDecimal impostoDebitado;

    /**
     * Gets the value of the numeroECF property.
     * 
     */
    public int getNumeroECF() {
        return numeroECF;
    }

    /**
     * Sets the value of the numeroECF property.
     * 
     */
    public void setNumeroECF(int value) {
        this.numeroECF = value;
    }

    /**
     * Gets the value of the baseCalculo property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getBaseCalculo() {
        return baseCalculo;
    }

    /**
     * Sets the value of the baseCalculo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setBaseCalculo(BigDecimal value) {
        this.baseCalculo = value;
    }

    /**
     * Gets the value of the tipoAliquota property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoAliquota() {
        return tipoAliquota;
    }

    /**
     * Sets the value of the tipoAliquota property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoAliquota(String value) {
        this.tipoAliquota = value;
    }

    /**
     * Gets the value of the valorAliquota property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValorAliquota() {
        return valorAliquota;
    }

    /**
     * Sets the value of the valorAliquota property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValorAliquota(BigDecimal value) {
        this.valorAliquota = value;
    }

    /**
     * Gets the value of the impostoDebitado property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getImpostoDebitado() {
        return impostoDebitado;
    }

    /**
     * Sets the value of the impostoDebitado property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setImpostoDebitado(BigDecimal value) {
        this.impostoDebitado = value;
    }

}
