//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.04 at 07:13:49 PM BRT 
//


package com.dieboldnixdorf.frentecaixa.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Calendar;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * <p>Java class for TipoRodapeLojaType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TipoRodapeLojaType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="quantidadeTotalClientesLoja" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="quantidadeClientesPerifericosLoja" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="dataMovimento" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TipoRodapeLojaType", propOrder = {
    "quantidadeTotalClientesLoja",
    "quantidadeClientesPerifericosLoja",
    "dataMovimento"
})
@JsonPropertyOrder({ 
    "quantidadeTotalClientesLoja",
    "quantidadeClientesPerifericosLoja",
    "dataMovimento"
})
public class TipoRodapeLojaType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected BigDecimal quantidadeTotalClientesLoja;
    @XmlElement(required = true)
    protected BigDecimal quantidadeClientesPerifericosLoja;
    @XmlSchemaType(name = "dateTime")
    @JsonProperty("dataMovimento")
    @JsonSerialize(using = DataMovimentoSerializer.class)
    protected Calendar dataMovimento;

    /**
     * Gets the value of the quantidadeTotalClientesLoja property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getQuantidadeTotalClientesLoja() {
        return quantidadeTotalClientesLoja;
    }

    /**
     * Sets the value of the quantidadeTotalClientesLoja property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setQuantidadeTotalClientesLoja(BigDecimal value) {
        this.quantidadeTotalClientesLoja = value;
    }

    /**
     * Gets the value of the quantidadeClientesPerifericosLoja property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getQuantidadeClientesPerifericosLoja() {
        return quantidadeClientesPerifericosLoja;
    }

    /**
     * Sets the value of the quantidadeClientesPerifericosLoja property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setQuantidadeClientesPerifericosLoja(BigDecimal value) {
        this.quantidadeClientesPerifericosLoja = value;
    }

    /**
     * Gets the value of the dataMovimento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Calendar getDataMovimento() {
        return dataMovimento;
    }

    /**
     * Sets the value of the dataMovimento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataMovimento(Calendar value) {
        this.dataMovimento = value;
    }

}
