//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.11 at 03:35:05 PM BRST 
//


package com.dieboldnixdorf.frentecaixa.domain;

import java.io.Serializable;
import java.math.BigDecimal;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;


/**
 * 
 *     			Itens de vendas por setor a cada hora (atualização do
 *     			arquivo nas horas cheias).
 *     		
 * 
 * <p>Java class for VendaSetorHoraPayloadType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VendaSetorHoraPayloadType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="numeroSetor" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="valorTotalVendaSetor" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="quantidadeItensVendidos" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="quantidadeClienteSetor" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="quantidadeClientesPerifericosSetor" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VendaSetorHoraPayloadType", propOrder = {
    "numeroSetor",
    "valorTotalVendaSetor",
    "quantidadeItensVendidos",
    "quantidadeClienteSetor",
    "quantidadeClientesPerifericosSetor"
})
@JsonPropertyOrder({ 
    "numeroSetor",
    "valorTotalVendaSetor",
    "quantidadeItensVendidos",
    "quantidadeClienteSetor",
    "quantidadeClientesPerifericosSetor"
})
public class VendaSetorHoraPayloadType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    protected int numeroSetor;
    @XmlElement(required = true)
    @JsonProperty("valorTotalVendaSetor")
    @JsonSerialize(using = BigDecimalSerializer.class)
    protected BigDecimal valorTotalVendaSetor;
    @XmlElement(required = true)
    @JsonProperty("quantidadeItensVendidos")
    @JsonSerialize(using = BigDecimal3Serializer.class)
    protected BigDecimal quantidadeItensVendidos;
    @XmlElement(required = true)
    protected Long quantidadeClienteSetor;
    @XmlElement(required = true)
    protected Long quantidadeClientesPerifericosSetor;

    /**
     * Gets the value of the numeroSetor property.
     * 
     */
    public int getNumeroSetor() {
        return numeroSetor;
    }

    /**
     * Sets the value of the numeroSetor property.
     * 
     */
    public void setNumeroSetor(int value) {
        this.numeroSetor = value;
    }

    /**
     * Gets the value of the valorTotalVendaSetor property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValorTotalVendaSetor() {
        return valorTotalVendaSetor;
    }

    /**
     * Sets the value of the valorTotalVendaSetor property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValorTotalVendaSetor(BigDecimal value) {
        this.valorTotalVendaSetor = value;
    }

    /**
     * Gets the value of the quantidadeItensVendidos property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getQuantidadeItensVendidos() {
        return quantidadeItensVendidos;
    }

    /**
     * Sets the value of the quantidadeItensVendidos property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setQuantidadeItensVendidos(BigDecimal value) {
        this.quantidadeItensVendidos = value;
    }

    /**
     * Gets the value of the quantidadeClienteSetor property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getQuantidadeClienteSetor() {
        return quantidadeClienteSetor;
    }

    /**
     * Sets the value of the quantidadeClienteSetor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setQuantidadeClienteSetor(Long value) {
        this.quantidadeClienteSetor = value;
    }

    /**
     * Gets the value of the quantidadeClientesPerifericosSetor property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getQuantidadeClientesPerifericosSetor() {
        return quantidadeClientesPerifericosSetor;
    }

    /**
     * Sets the value of the quantidadeClientesPerifericosSetor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setQuantidadeClientesPerifericosSetor(Long value) {
        this.quantidadeClientesPerifericosSetor = value;
    }
}
