//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.01 at 10:44:21 PM BRT 
//


package com.dieboldnixdorf.frentecaixa.domain;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import com.dieboldnixdorf.frentecaixa.domain.TipoFormasPagamentosType;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;


/**
 * <p>Java class for SangriaPDVPayloadType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SangriaPDVPayloadType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="numeroPDV"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
 *               &lt;maxExclusive value="999"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="DRT"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}long"&gt;
 *               &lt;maxExclusive value="999999999"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="dataSangria" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="formasPagamentos" type="{http://www.dieboldnixdorf.com/frentecaixa/TipoFormasPagamentos}TipoFormasPagamentosType" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SangriaPDVPayloadType", propOrder = {
	"siglaLoja",
    "numeroPDV",
    "drt",
    "dataSangria",
    "formasPagamentos"
})
@JsonPropertyOrder({ 
	"siglaLoja",
    "numeroPDV",
    "drt",
    "dataSangria",
    "formasPagamentos"
})
public class SangriaPDVPayloadType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    protected String siglaLoja;
    protected Long numeroPDV;
    @XmlElement(name = "drt")
    protected long drt;
    @XmlElement(required = true, type = String.class)
    @XmlSchemaType(name = "dateTime")
    @JsonProperty("dataSangria")
    @JsonSerialize(using = DataSangriaSerializer.class)
    protected Calendar dataSangria;
    @XmlElement(required = true)
    protected List<TipoFormasPagamentosType> formasPagamentos;

    /**
     * Gets the value of the siglaLoja property.
     *
     * @return the sigla loja
     */
    public String getSiglaLoja() {
		return siglaLoja;
	}

    /**
     * Sets the value of the siglaLoja property.
     * 
     */
	public void setSiglaLoja(String siglaLoja) {
		this.siglaLoja = siglaLoja;
	}

	/**
     * Gets the value of the numeroPDV property.
     * 
     */
    public Long getNumeroPDV() {
        return numeroPDV;
    }

    /**
     * Sets the value of the numeroPDV property.
     * 
     */
    public void setNumeroPDV(Long value) {
        this.numeroPDV = value;
    }

    /**
     * Gets the value of the drt property.
     * 
     */
    public long getDrt() {
        return drt;
    }

    /**
     * Sets the value of the drt property.
     * 
     */
    public void setDrt(long value) {
        this.drt = value;
    }

    /**
     * Gets the value of the dataSangria property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Calendar getDataSangria() {
        return dataSangria;
    }

    /**
     * Sets the value of the dataSangria property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataSangria(Calendar value) {
        this.dataSangria = value;
    }

    /**
     * Gets the value of the formasPagamentos property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the formasPagamentos property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFormasPagamentos().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TipoFormasPagamentosType }
     * 
     * 
     */
    public List<TipoFormasPagamentosType> getFormasPagamentos() {
        if (formasPagamentos == null) {
            formasPagamentos = new ArrayList<TipoFormasPagamentosType>();
        }
        return this.formasPagamentos;
    }

}
