//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.01 at 10:44:21 PM BRT 
//


package com.dieboldnixdorf.frentecaixa.domain;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.dieboldnixdorf.frentecaixa.domain.TipoFormaPagamentoType;


/**
 * <p>Java class for TipoFormasPagamentosType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TipoFormasPagamentosType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="formasPagamentos" type="{http://www.dieboldnixdorf.com/frentecaixa/TipoFormaPagamento}TipoFormaPagamentoType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TipoFormasPagamentosType", propOrder = {
    "formasPagamentos"
})
public class TipoFormasPagamentosType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected TipoFormaPagamentoType formasPagamentos;

    /**
     * Gets the value of the formasPagamentos property.
     * 
     * @return
     *     possible object is
     *     {@link TipoFormaPagamentoType }
     *     
     */
    public TipoFormaPagamentoType getFormasPagamentos() {
        return formasPagamentos;
    }

    /**
     * Sets the value of the formasPagamentos property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoFormaPagamentoType }
     *     
     */
    public void setFormasPagamentos(TipoFormaPagamentoType value) {
        this.formasPagamentos = value;
    }

}
