//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.01 at 10:44:21 PM BRT 
//


package com.dieboldnixdorf.frentecaixa.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;


/**
 * 
 * 				Identificação do código de barras contido na banana que
 * 				transportará o dinheiro, somente quando TIPO MOEDA = 2.
 * 			
 * 
 * <p>Java class for TipoFormaPagamentoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TipoFormaPagamentoType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="formaPagto"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="numeroFormaPagto"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
 *               &lt;maxExclusive value="99"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="valorSangria" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="tipoMoeda"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
 *               &lt;maxExclusive value="9"/&gt;
 *               &lt;enumeration value="0"/&gt;
 *               &lt;enumeration value="1"/&gt;
 *               &lt;enumeration value="2"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="numeroBanana" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TipoFormaPagamentoType", propOrder = {
    "formaPagto",
    "numeroFormaPagto",
    "valorSangria",
    "tipoMoeda",
    "numeroBanana"
})
@JsonPropertyOrder({ 
    "formaPagto",
    "numeroFormaPagto",
    "valorSangria",
    "tipoMoeda",
    "numeroBanana"
})
public class TipoFormaPagamentoType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected String formaPagto;
    protected int numeroFormaPagto;
    @XmlElement(required = true)
    @JsonProperty("valorSangria")
    @JsonSerialize(using = BigDecimalSerializer.class)
    protected BigDecimal valorSangria;
    protected int tipoMoeda;
    protected String numeroBanana;

    /**
     * Gets the value of the formaPagto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormaPagto() {
        return formaPagto;
    }

    /**
     * Sets the value of the formaPagto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormaPagto(String value) {
        this.formaPagto = value;
    }

    /**
     * Gets the value of the numeroFormaPagto property.
     * 
     */
    public int getNumeroFormaPagto() {
        return numeroFormaPagto;
    }

    /**
     * Sets the value of the numeroFormaPagto property.
     * 
     */
    public void setNumeroFormaPagto(int value) {
        this.numeroFormaPagto = value;
    }

    /**
     * Gets the value of the valorSangria property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValorSangria() {
        return valorSangria;
    }

    /**
     * Sets the value of the valorSangria property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValorSangria(BigDecimal value) {
        this.valorSangria = value;
    }

    /**
     * Gets the value of the tipoMoeda property.
     * 
     */
    public int getTipoMoeda() {
        return tipoMoeda;
    }

    /**
     * Sets the value of the tipoMoeda property.
     * 
     */
    public void setTipoMoeda(int value) {
        this.tipoMoeda = value;
    }

    /**
     * Gets the value of the numeroBanana property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroBanana() {
        return numeroBanana;
    }

    /**
     * Sets the value of the numeroBanana property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumeroBanana(String value) {
        this.numeroBanana = value;
    }

}
